RAID = [
    "TEᖇIII ᗩᗰᗰᗩ Kᗩ ᗷSᗪᗩ ᗰᗩI ᗷOᗰᗷ ᒪᗩGᗩKᖇ ᒍᒪᗩ ᗪᑌᑎGᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ💦🍆🍑😍",
    "ᗷSᗪK TEᖇII Gᗩᗩᑎᗪ ᖴᗩᗩᗪ ᗪᑌᑎGᗩ ᒪᗩᐯᗪE Kᗩᒪᗩᑭ ᗰᗩT😂😂🔥",
    "TEᖇII ᗷEᕼEᑎ KI ᑕᕼᑌT ᖴᗩᗩᗪ KE ᑌSᗰE ᗪYᑎᗩᗰITE ᒪᗩGᗩ KE ᗷᒪᗩST KᗩᖇᗪᑌᑎGᗩ ᗷᕼOSᗪIKE🧨👻☠️",
    "TEᖇII ᗰᗩᗩ Kᗩ ᖇᗩᑭE KᗩᖇKE ᑌSKE 1000 TᑌKᗪE KᗩᖇKE KᑌTTO KO KᕼIᒪᗩ ᗪᑌᑎGᗩ ᖇᗩᑎᗪI KE ᗷᗩᑕᕼᕼE👻💦🍆🔥",
    "TEᖇII ᗰᗩ KI ᑕᕼᑌT ᗰᗩI ᒍᗩᗷ ᗰEᖇᗩ ᒪᗩᐯᗪᗩ ᒍᗩᗩTᗩ ᕼᗩI Tᗩᗷ TEᖇII ᗰᗩᗩ ᗷOᕼOT KᕼᑌSᕼ ᕼOTI ᕼᗩI ᗷSᗪK💦👻🍆🍑",
    "TEᖇII ᗰᗩᗩ KI ᑕᕼᑌT ᖴᗩᗩᗪ ᗪI ᗷSᗪK ᗩᗷ KᗩᒪᗩᑭᗩT ᗷETᗩ ᗷEᕼEᑎ ᑕᕼOᗪᑎE KI TᗩYᗩᖇI Kᗩᖇ ᖇᗩᕼᗩ ᕼᑌ☠️💦🍆🍑🔥",
    "ᗷᕼOSᗪIKE SᑭEEᗪ ᗪEKᕼ ᖇᗩᕼᗩ GᒪᗩᗪIᗩTOᖇ ᗷOT ᕼᗩI Gᗩᗩᑎᗪ ᖴᗩᗩᗪ Kᖇ ᖇᗩKᕼ ᗪEGᗩ TEᖇIII ᗰᗩᗪᗩᖇᑕᕼOᗪ🔥🔥👻😈",
    "TEᖇII ᗰᗩᗩ Kᗩᒪᑭ ᖇᗩᕼI ᕼᗩI ᑌSKO Sᗩᗰᗷᕼᗩᒪ😈💦 ᗩᗷᕼI TEᖇII ᗷEᕼEᑎ KO KᗩᒪᑭᗩᑌᑎGᗩ ᗷSᗪK 👻💦🍆🍑🔥",
    "ᗷᗩᗩᑭ SE ᑭᗩᑎGᗩ ᒪEKᖇ GᗩᒪTI KᗩᖇᗪI ᗷETE ᗩᗷ Gᗩᑎᗪᗩ ᑕᕼᑌᗪEGᗩ Tᑌ😈🔥💦🍆🍑",
    "TEᖇII ᗰᗩᗩ KO Kᒪᑭᗩ Kᒪᑭᗩ KE ᑕᕼOᗪᑌᑎGᗩ ᗷᕼOSᗪIKE 🍆🍑🔥",
    "ᗷᕼOSᗪIKE TEᖇII ᗰᗩᗩ Kᗩ ᗰᗰS ᖇEᑕOᖇᗪ KᗩᖇKE ᙭ᑎ᙭᙭.ᑕOᗰ ᗩᑌᖇ ᑭOᖇᑎᕼᑌᗷ.ᑕOᗰ ᑭᖇ ᗪᗩᒪᑌᑎGᗩ😂😘🔥",
    "TEᖇII ᗰᗩ ᖇOᘔ ᖇEᗪᒪIGᕼT ᑭE 1000 ᗰᗩI Gᗩᗩᑎᗪ ᗩᑌᖇ ᑕᕼᑌT ᗪETI ᕼᗩI😂😂🍑",
    "TEᖇI ᗷEᕼEᑎ KO ᖇOᘔ ᗪEKᕼTᗩ ᕼᑌ ᑭOᖇᑎᕼᑌᗷ.ᑕOᗰ ᑭE ᖇOᘔ SᗩᗩᒪI 10 ᒪOGO Kᗩ ᒪᑌᑎᗪ EK SᗩTᕼ ᒪETI ᕼᗩI😂💦👻",
    "TEᖇII ᗰᗩᗩ Kᗩ ᗷSᗪᗩ ᗩᗷ ᑕᕼᑌᗪ GᗩYᗩ TOᕼ Kᗩᒪᗩᑭ ᖇᗩᕼᗩ ᖇᑎᗪI Kᗩ ᗷᗩᑕᕼᕼᗩ😈😂😘",
    "TEᖇII ᗰᗩᗩ KI ᑕᕼᑌT ᖴᗩᗩᗪ KE ᗷᗩᑕᕼᕼE ᑎIKᗩᒪ ᗪᑌᑎGᗩ SᗩᗩᖇE ᗷSᗪK😂😘👻",
    "TEᖇE Gᗩᗩᑎᗪ ᗰᗩI 10 ᖴEET Kᗩ Gᗩᖇᗩᗰ ᖇOᗪ ᗪᗩᗩᒪᗪᑌᑎGᗩ ᗷSᗪK ᖴIᖇ ᗰᑌᕼ SE ᕼᗩGEGᗩ😂🔥🍆",
    "TEᖇII ᗷEᕼEᑎ KI KᗩᗩᒪI ᑕᕼᑌT ᗰᗩI ᗰEᖇᗩ ᒪᑌᑎᗪ ᗪᗩᗩᒪKE ᖇOᘔ ᗷᗩᑕᕼᕼᗩ ᑭᗩIᗪᗩ KᗩᖇᑌᑎGᗩ😂🍆💦",
    "ᗩᒍEEᗷ ᗷᗩᗩT ᕼᗩI ᗷSᗪK Tᑌ ᗰEᖇᗩ ᗷETᗩ ᗩᑌᖇ Sᗩᗩᒪᗩ ᗪOᑎO ᒪᗩGTᗩ ᕼᗩI ᗩISE KᗩISE Sᗩᗰᗩᒍ ᑎᗩᕼI ᖇᗩᕼᗩ 😂👻😈",
    "TEᖇII ᗰᗩᗩ KO ᑕᕼOᗪKᖇ TᑌᒍᕼE ᑭᗩIᗪᗩ KIYᗩ ᖴIᖇ TEᖇII ᗷEᕼEᑎ KO ᑕᕼOᗪKᖇ ᑌSKᗩ ᗷᗩᑕᕼᕼᗩ ᑭᗩIᗪᗩ KIYᗩ💦🍆👻",
    "ᑭᗩᑭᗩ SE ᒪᗩᗪᑎE KI ᗩᑌKᗩT ᑎᗩᕼI ᗷSᗪK TEᖇI Gᗩᗩᑎᗪ ᗰᖇᗩ 😂😈🔥",
    "ᑭEᕼᒪE ᗰᗩIᑎ TEᖇEKO ᑕᕼᗩKᑎᗩ ᗪEGᗩ, ᖴIᖇ ᗪᗩᖇᑌ ᑭIᒪᗩYEGᗩ, ᖴIᖇ ᒍᗩᗷ ᗩᗩᑭ ᗪIᗰᗩG sE ᑎᗩᕼI ᒪ*ᑎᗪ sE sOᑕᕼOGE, Tᗩᗷ ᗷOᒪEGᗩ..",
    "तेरी छोटी बहन साली कुतिया की चिकनी चिकनी बिना बाल वाली चूत के चिथड़े उड़ा डालूंगा अपने 9 इंच लंबे लंड से , समझा बेटीचोद साले बहन के लौड़े** \ᑎ\ᑎतेरा बाप हूं मैं मादरचोद साले Gᗩᑎᗪᑌ , तू मेरी नाजायज औलाद है , जा जाके पूछ अपनी मम्मी साली रंडी से \ᑎ\ᑎतेरी अप्पी बता रही थी कि तू बहुत बड़ा मादर चोद है, तूने ही अपनी अम्मी को चोद कर अपनी अप्पी पैदा की, और तू बहुत बड़ा गांडू भी है, कितने रेट है तेरे गाड़ मरवाने के ??\ᑎतेरी मां की चूत को पिकाचू और ग्लेडिएटर्स हमेशा पेलते हैं।\ᑎऔर ये भी बता कि गाड़ मरवाता है, कंडोम लगा के या बिना कण्डोम के ? तेल लेकर तू आएगा या मैं ही जापानी तेल लेकर आउ ?",
    "TEᖇI ᗩᗰᗰY KE sᗩTᕼ ᗰᗩI ᖇOᒪE ᑭᒪᗩY KᗩᖇᑌᑎGᗩ🤣🤣🤣🤣🤣🤣ᑌsKO ᗰᗩᒪIK KI ᗯIᖴE ᗷᗩᑎᗩᑌᑎGᗩ ᗩᑌᖇ Kᕼᑌᗪ ᗪᖇIᐯEᖇ ᗷᗩᑎKE ᑭEᒪᑌᑎGᗩ ᑌsKO!",
    "TEᖇI ᗰᗩᗩ KI Gᗩᗩᗩᗩᑎᗪ ᗰE ᗪᗩᑎᗪᗩᗩ ᗪᗩᗩᒪ KE ᗪᗩᑎᗪᗪᗩ TOᗪᗪ ᗪᑌᑎGᗩᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ ᗷᗩᗩᑭ ᕼᑌ TEᖇᗩ ᗷEᕼEᑎ KE ᒪᑌᑎᗪᗪᗪ",
    "ᑭᕼOOᒪ ᗰᑌᖇᒍᕼᗩTE ᗩᑕᕼᕼE ᑎᗩᕼI ᒪᗩGTE ᗩᗩᑭ ᒪᗩᑎᗪ KᕼᑌᒍᗩTE ᗩᑕᑕᕼE ᑎᗩᕼI ᒪᗩGTE YEᕼI ᑌᗰᗩᖇ ᕼᗩI ᑕᕼOᗪᑎE KI YᗩᗩᖇO ᗩᗩᑭ ᗷᗩTᕼᖇOOᗰ ᗰEIᑎ ᕼIᒪᗩᗩTE ᗩᑕᑕᕼE ᑎᗩᕼI ᒪᗩGTE.",
    "TEᖇI ᗷEᕼᑎ KO ᗷOᒪᑌᑎGᗩ KI ᗰEᖇE ᒪIYE ᑭᗩᗩᑎI ᒪᗩO ᗩᑌᖇ ᒍᗷ ᗯO ᑭᗩᗩᑎI ᒪEᑎE KE ᒪIYE ᒍᕼᑌKEGI TᗷI ᑭEEᑕᕼE sE ᑌTᕼᗩ KE ᑭEᒪ ᗪᑌᑎGᗩ",
    "ᑕᕼIᑎᗩᗩᒪ KE GᗩᗪᗪE KE ᑎIᑭᑭᒪE KE ᗷᗩᗩᒪ KE ᒍOOᑎ- ᑭᖇOsTITᑌTE’s ᗷᖇEᗩsT’s ᑎIᑭᑭᒪE’s ᕼᗩIᖇ’s ᒪIᑕE",
    "TEᖇI ᗰᗩᗩ KI Gᗩᗩᑎᗪ ᗰEIᑎ ᗩᗷᕼI ᗷᕼᗩᖇ ᗷᕼᗩᖇ KE GᗩᗩᒪI ᗪETᗩ ᕼᑌᑎ ᗰᗩᗪᗩᖇᑕᕼOᗪ ᗷᕼOsᗪIKE ᖇᑌK TEᖇI ᗰᗩᗩ Kᗩ ᗷᕼOsᗪᗩ ᖇᗩᑎᗪI Kᗩ ᑭIᒪᒪᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ ᑕᕼᑌs ᒪE ᗰEᖇᗩ ᒪOᗪᗩ ᗷᕼOsᗪIKE",
    "Sᗩᗩᗯᗩᑎ Kᗩ ᗰᗩᕼIᑎᗩ ᑭᗩᗯᗩᑎ KᗩᖇE sᕼOᖇ ᒍᗩKE Gᗩᑎᗪ ᗰᗩᖇᗩ ᗷsKᗪ KᗩᕼI ᗩᑌᖇ.",
    "ᕼEY ᗰEᖇE ᗷETE KᗩIsE ᕼO ᗷETᗩ Tᑌᗰ\ᑎᑌss ᖇᗩᗩT ᒍᗩᗷ ᗰᗩIᑎE TEᖇI ᗰᗩᗩ ᑕᕼOᗪᗩ Tᕼᗩ ᒍIsKE 9 ᗰᗩᕼIᑎE ᗷᗩᗩᗪ Tᑌᗰ ᑭᗩIᗪᗩ ᕼᑌE ᗷᕼOT ᗰᗩᘔᗩ ᗩᗩYᗩ Tᕼᗩ ᗰᑌᒍᕼE ᗩᑌᖇ TEᖇI ᗰᗩᗩ KO ᗷᕼI!!",
    "TEᖇI ᗰᗩᗩ KI Gᗩᗩᑎᗪ ᗰEIᑎ ᗩᗷᕼI ᗷᕼᗩᖇ ᗷᕼᗩᖇ KE GᗩᗩᒪI ᗪETᗩ ᕼᑌᑎ ᗰᗩᗪᗩᖇᑕᕼOᗪ ᗷᕼOsᗪIKE ᖇᑌK TEᖇI ᗰᗩᗩ Kᗩ ᗷᕼOsᗪᗩ ᖇᗩᑎᗪI Kᗩ ᑭIᒪᒪᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ ᑕᕼᑌs ᒪE ᗰEᖇᗩ ᒪOᗪᗩ ᗷᕼOsᗪIKE",
    "TEᖇIIIIIIII ᗰᗩᗩᗩᗩᗩᗩᗩᗩᗩᗩ KI ᑕᕼᑌTTTTT ᗰEEEEEEEEE GᕼOᗪEEEE Kᗩ ᒪᑌᑎᗪᗪᗪᗪᗪᗪᗪ ᗰᗩᗪᗩᖇᑕᕼOᗪᗪᗪᗪᗪᗪᗪ GᗩSTI KE ᗷᗩ᙭ᕼEEEEE",
    "TEᖇI ᗰᗩᗩ Kᗩ ᗰᗩᖇS ᑭE KOTᕼᗩ KᕼᑌᒪᗯᗩᗩᑌᑎGᗩ 🔥😂",
    "G4ᑎᗪ😈 ᗰ3 TEᖇI ᏞᎾᕼᎬ🥒🥒  KI ᏒᎾᎠ ᗪ4ᒪᗪᑌᑎGᗩ😸😸ᗷᎥᏞᏞᎥ 😺 ᗷᎪᏁᎪ  K3 ᑕᕼ0ᗪᑌᑎG4💦💦👅👅 T3ᖇ ᎪᗰᗰᎽ  K0👻👻ᏆᎬᏃᎪᗷ😍😍  ᎠᎪᎪᏞ  ᎠᑌᏁᎶᎪ T3ᖇ1👄ᗷ3ᕼᑎ K3😜😜😜 ᗷ00ᖇ 👙👙ᗰEᗰ4ᗪ3ᖇᑕᕼ0ᗪ🙈🙈ᒍᕼ4ᑎT3🖕 ᏁᎾᏟᕼᏞᑌᏁᎶᎪ🥳🥳  ᏆᎬᎬ1 ᗷᎬᕼᏁ  K1🍌🍌Sᑌ4ᖇ K1 😈ᏁᎪsᎪᏞ Ꮮ0ᎳᎠᑌ 🙈T3ᖇ1 ᎪᗰᗰᎽ😺😺😺  K0 ᖴ4ᑎS1 ᒪᗩGᗩ ᗪᑌᑎG4😹😹💦💦 G44ᑎᗪ 💣ᗰE TEᖇ1 ᗩᑕ1ᗪ🍆🍆 ᗪ44ᒪᗪᑌᑎG4🍒TᕼᎪᏁᎠᎬ 😹 ᏢᎪᎪᏁᎥ SE 👙ᏁᎬᕼᏞᎪ K3 ᑕᕼ0ᗪᑌᑎG4 🥳🥳TEᖇ1 ᑕᕼᕼOT1💦💦 ᗷ3ᕼᑎ KO😹TᗩTT1💩💩 KᖇᗪᑌᑎG4 TEᖇ1  Ꮆᖴ  KE😺😺 ᗰᑌᕼ  ᏢᎬ 👅👅😈",
    "ᗰᗩᗪᗩᖇᑕᕼOOᗪOO.••>___βħΔG βΣτΔ βħΔG τΣᖇΔΔΔ βΔᑭᑭᑭ ΔΥΔΔ___🔥ᖇυKKKK ᖇυKK βΣτΔΔ βᕼΔGGG KΔᕼΔ ᖇΔᕼΔΔ ᕼΔII ΔβᕼI τΟ τΣᖇI мΔΔ ζᕼυδΣGII ᖇυKK☜☜☜мΔτᒪΔββ βΔβΥ мΔᖇᐯΔᒍΣΣΣ мΔПΣGIII👅👅👅👅>>>>◑︿◐ᒍᕼΔПτ βᕼΔᖇᖇ KI ΔυKΔτ  ПΔᕼI τΣᖇI Δυᖇ βΔᑭᑭᑭ ςΣ ᒪΔδΣGΔΔΔ◑︿◐<<<<<τΣᖇI βΣᕼΣП KI GΔПδ мΣ ᒪΟᕼΣ KΔ ᖇΟδδ δΔᒪ δυПGΔ🎋🎋🎋βIᒪᒪII βΔПΔ KΣ ζᕼΟδυПGΔ τΣᖇI βΣᕼΣП KΟΟ▀▄▀▄▀▄τΣᖇI мΔΔ KI GΔПδδ мΣ βΣΔᖇ KI βΟττᒪΣ δΔᒪ KΣ ᖴΟδδ δυПGΔ🍾🍾🍾________βᕼΔGGG δΔᖇᒪIПG βᕼΔGGG___GΔПδδ βΔζζᕼΔ KΣΣ βᕼΔGGGG____βΔᑭ ΔΥΔ τΣᖇΔ >>>>>◑︿◐ᒍᕼΔПτ βᕼΔᖇᖇ KI ΔυKΔτ  ПΔᕼI τΣᖇI Δυᖇ βΔᑭᑭᑭ ςΣ ᒪΔδΣGΔΔΔ◑︿◐<<<<<τΣᖇI βΣᕼΣП KI GΔПδ мΣ ᒪΟᕼΣ KΔ ᖇΟδδ δΔᒪ δυПGΔ🎋🎋🎋βIᒪᒪII βΔПΔ KΣ ζᕼΟδυПGΔ τΣᖇI βΣᕼΣП KΟΟ▀▄▀▄▀▄ΨΩᑌᖇ ҒΔTᕼΣᖇ ᕼΣᖇΣ😎😎",
    "ᗰᗩᗪᗩᖇᑕᕼOᗪᗪ😁-):-ᑭ:-\:'(:3:'(:'((^-)(^-):3:3:-/:-/:-/:-/:-/:-/:-/:-/:-/:-/:-/:-/:-/:-/:-/:-/:-/:-/:-/:-/ ᗷᕼEᑎ KE ᒪOᗪE ᗩᑭᑎE ᗷᗩᗩᑭ KO🤥🤥 ᗷ-)ᗷ-)ᗷ-)ᗷ-)ᗷ-)ᗷ-)ᗷ-)ᗷ-)ᗷ-)ᗷ-)ᗷ-)ᗷ-)ᗷ-)(^O^)(^O^)GᗩᗩᒪI ᗪEGᗩ ᖇᗩᑎᗪI ᗯᗩᒪE 🤒🤒🤒(^O^)(^O^)(^O^)(^O^)(^O^)ᗩᑭᑎI ᗰᗩ SE ᑭᕼᑌᑕᕼ KI TEᖇI ᗰᗩᗩᗩ ᑎE ᗰEᖇI ᗰᑌTᕼ KᗩISE ᗰᗩᖇI TᕼI SᗩᒪE ᗷᕼOT ᗷᗩᗪ TᗩᖇIKE SE TEᖇI ᗰᗩᗩ KI Gᕼᗩᑎᗪ ᗰᗩᖇI  TᕼI😂😂😂😂 -/:-/:-/:-/:-/:-/:-/:-/:-/:-/:ᗷ-)ᗷ-)ᗷ-)ᗷ-)ᗷ-)ᗷ-)ᗷ-)TEᖇI ᗰᗩᗩ KO ᒪOᑕᗩᒪ ᑕOᑎᗪOᗰ SE ᑕᕼOᗪᗩ 🌎🌎🌎🌎🌎🌎ᕼᗩ TO Gᕼᗩᑎᗪ KE ᗩᑎᗪᗩᖇ ᑕOᑎᗪOᗰ ᗷᒪᗩST ᕼOGYᗩ Oᖇ ᗷᗷᕼᗩᗪᗯE Tᑌ ᒪOᗪᗩ ᑭᗩKᗩᗪ KE ᗷᕼᗩᖇ ᗩᗩGYᗩ ᗷᕼOSᗪIKE ᗰᗩᗪᗩᖇᑕᕼOᗪᗷ-):-/:-/:-/:-/:-/:-/:-/:-/:-/:-/:-/:-/:-/:-/:-/:-/:-/:-/ ᑕᕼᗩᒪᒪ ᗩᗷᗷ ᑎIKKᒪ ᗷᗷᕼᗩᗩᗪᗯEE😒😒",
    "ᑌss ᖇᗩᗩT ᗷᗩᗪᗩ ᗰᗩᘔᗩ ᗩᗩYᗩ ᒍᗩᗷ GᒪคᗪIᗩTøᖇ͢͢͢𝓼 TEᖇI ᗰᗩᗩ KE ᑌᑭᗩᖇ ᗩᑌᖇ TEᖇI ᗰᗩᗩ GᒪคᗪIᗩTøᖇ͢͢͢𝓼 KE ᑎEEᑕᕼE\ᑎ\ᑎOᕼ YEᗩᕼ!! Oᕼ YEᗩᕼ!!",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰEIᑎ ᗪIYᗩ GᒪᗩᗪIᗩTOᖇs ᑎE ᗰOOT!!",
    "ᗰᗩᗩᗩᗩᗩᗪᗩᗩᖇᑕᑕᕼOᗪ TEEEᖇᖇᖇᖇII ᗰᗩᗩᗩᗩᗩ KOO\ᑎ ᑎᗩᑎGᗩ KᗩᖇKE ᑭIKᗩᑕᕼᑌ ᗩᑌᖇ ᗪEEᑭᗩK😈 SᗩᗪᗩK KE ᗷEEᑕᕼ ᗰEIᑎ ᒪEEETᗩᗩᗩ KE ᑭEᒪEGᗩ\ᑎ🤘🤫🤣🤣🤤",
    "SᗩᗩᗩᒪEEEE  TEEᖇIIII ᗰᗩᗩᗩᗩᗩ KIIIIII ᑕᕼᑌTTT ᗩESEEEEE ᗰᗩᗩᖇᖇᑌᑎGᗩᗩᗩ ᑎᗩᗩᗩᗩ\ᑎKIIII SᑌᖇᗩᑎG ᗷᑌᑎᑎᑎ ᒍᗩYEGI ᗷEᕼᗩᑎᑕᕼOᗪ\ᑎᑌSᗰEEE ᒪᗩᗩᗩᑎᗪᗪ ᗰIᑎE ᗷIᑕᕼᗩᗩᗩᗩᗩᗩ KEEEEEEEE ᑌᗪᗩᗩᗩᗩᗩ ᗪᑌᑎGᗩᗩᗩᗩᗩ\ᑎTEEEEᖇIIIIIIII ᗰᗩᗩᗩᗩᗩᗩ Kᗩᗩᗩᗩᗩ ᗷᕼOSᗪᗩᗩᗩᗩ ᑌᗪᗪᗪᗪᗪᗪ ᒍᗩᗩᗩYEGᗩᗩᗩ ᗰᗩᗩᗪᗩᖇᑕᕼO\ᑎ🤘😂😜😋🤭🤣🤣🤫🤫🤫🤫🤧🤧🤧🤧🤧😇😇😇😇🥱🥱🥱",
    "TEEEᖇIIIIII ᗰᗩᗩᗩᗩᗩ KIIIII ᑕᕼᑌTTTTT ᗰEIᑎ ᗩEᖇOᑭᒪᗩᑎE ✈️🛫✈️🛫 ᗪᗩᗩᗩᗩᗩᒪ KEEEEE ᑌᗪᗩᗩᗩᗩᗩ ᗪᑌᑎGᗩ\ᑎ ᗰᗩᗩᗩᗩᗩᗪᗩᗩᗩᖇᑕᕼOᗪ\ᑎ🤤🤘Tᑌᑌᑌᑌᑌᑌᑌ ᗩᗩᑌᖇᖇ TEᖇIIIIII ᗷEᕼᗩᑎᑎᑎᑎᑎ IᑎᗪIᗩ ᗰEIᑎ ᑕᕼᑌᗪᗯᗩᗩᑎᗩᗩ\ᑎTEᖇIIIIIIII ᗰᗩᗩᗩᗩᗩᗩᗩᗩ ᗷᗩᗩᗩᗩᕼᗩᗩᗩᖇ ᑕᕼᑌᗪᗯᗩᗩᗩᗩᗩYEGIIII\ᑎKᗩᗷᕼIIIII ᗩᑌSTᖇᗩᒪIᗩ 🌏 KᗩᗷᕼI ᑌSᗩ KᗩᗷᕼI EᑎGᒪᗩᑎᗪ\ᑎ🤤🤤🤤🤤🤤🤤👅👅👅👅👄👄👄👄👄👄👄💋💋💋💋💋💋",
    "TEEEᖇIIIIII ᗰᗩᗩᗩᗩᗩᗩᗩ ᗷEEEᕼᗩᗩᗩᗩᑎ KEEEEE ᗷᕼOSᗩᗪE ᗰEIᑎ ᑭᗩTᗩᑎG\ᑎ ᗪᗩᗩᗩᗩᗩᗩᗩᗩᒪ KEEEEE ᑌᗪᗩᗩᗩᗩᗩ ᗪᑌᑎGᗩ\ᑎ ᗰᗩᗩᗩᗩᗩᗪᗩᗩᗩᖇᑕᕼOᗪ\ᑎ🤤🤤😂😂😂🤭😙😙😜😜😎😎",
    "😈😈👅👅👅👅👅💩💩💩💩👻👻👻👻👻👻👻☠️🤑🤑🤑🤑🎃🎃🎃🎃🎃🥵🥵🥵🥵🥵\ᑎTEEEEᖇᖇᖇIIIIIIII ᗰᗩᗩᗩᗩᗩᗩ ᗩEESEEE ᑕᕼOᗪI KI TEᖇIIIIIIII ᗰᗩᗩᗩᗩ ᗩESE ᕼI ᖇᗩᑎG ᗷIᖇᗩᗩᗩᑎGI ᕼOOOOO GYIIIIIII ᗷSᗪK ᗩᗷ TEᖇIIIIII ᗩᑌᖇ ᗷEᕼᗩᑎ KI ᗷᗩᗩᗩᗩᖇI ᗩᗷᗷᗷᗷᗷᗷ ᗪEEᑭᗩK ᑭEᒪEGᗩ ᗰᗩᗩᗪᗩᖇᑕᕼOᗪ Sᗩᗰᗷᕼᗩᗩᒪ KE Sᗩᗰᗷᕼᗩᗩᒪ SᗩKTᗩᗩᗩᗩᗩ ᕼᗩIIIIII TOOOOOOO🤤🤤🤤🤤👅👅👅👅👅",
    "ᗷᗩᗩᗩᗩᗩᑭ SEEEE ᑭᗩᗩᑎGᗩᗩᗩ ᒪEEEEE ᒪIYᗩᗩᗩᗩ ᗰᗩᗩᗩᗩᗩᗪᗩᗩᗩᖇᑕᕼOᗪ\ᑎ ᑕᕼᗩKKEE ᗪEKᕼ ᗩᗩᗩᗷᕼI TEᖇIIIIIIII ᗰᗩᗩᗩᗩᗩᗩᗩ KEISE ᑕᕼᑌᗪEEGIIIII ᗷSᗪK ᖇᗩᑎᗪE\ᑎ 🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤘🤘🤘🤘🤘🤘🤘",
    "TEᖇIIIIIIII ᗰᗩᗩᗩᗩᗩᗩ KE ᗷᕼOSᗩᗪE ᗰEIᑎ ᗪᗩᑎᗪᗩᗩᗩ ᗪᗩᗩᗩᗩᒪ KEEEE Kᕼᗩᗩᗩᗪᗩᗩᗩ Kᖇ ᗪᑌᑎGᗩ\ᑎ ᗰᗩᗩᗩᗩᗩᗪᗩᗩᗩᖇᑕᕼOᗪ\ᑎ😋🤤🤤🤤🤤🤤✈️✈️✈️🤤🤤🤤",
    "TEEᖇᖇᖇIIIII ᗰᗩᗩᗩᗩ KEEE ᑭᕼᗩᗩᗩTEEE ᗷᕼᕼOOSᗩᗩᗪE\ᑎ Kᗩᗩᗩᗩ SᕼIIIIIKᗩᗩᗩᗩᗩᖇIIII ᕼᗩᗩᗩIIIIII ᗪEEᑭᗩK SᗩᗩᒪE ᑕᕼᗩKKEE\ᑎ🤭🤤🤤🤨",
    "ᖇᗩᗩᗩᗩᑎᗪᗪᗪIIIIIIII KEEEEE ᑭIᒪᒪᒪᒪᒪᒪEE ᗰᗩᗩᗩᗩᗩᗪᗩᗩᗩᖇᑕᕼOᗪ😋😁",
    "𝗔𝗡𝗗𝗜 𝗕𝗔𝗡𝗗𝗜 𝗦𝗔𝗡𝗗𝗜 𝗠𝗔𝗔𝗗𝗔𝗥𝗖𝗛𝗢𝗗\ᑎ𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗕𝗘𝗛𝗔𝗡 𝗣𝗜𝗞𝗔𝗖𝗛𝗨 𝗣𝗘𝗟𝗘 𝗞𝗥𝗞𝗘 𝗥𝗔𝗡𝗗𝗜\ᑎ😆😆🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣👅👅😘😘",
    "ᗰᑌᗰᗰYYYY KOOOOO ᗷOᒪᒪᒪᒪ TEᒪᒪ ᒪGᗩᗩᗩᗩ KEEEEE ᖇᗩKᕼEEEE\ᑎTᕼᑌᑌᑌKKKK ᒪGᗩᗩᗩᗩᗩᗩ KEEEEEE ᗰᗩᗩᗩᗩᖇᑎEEEE ᑎᕼI ᗪEETI ᐯOOOOOO\ᑎ🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤",
    "𝔸𝔹𝔼 𝕄𝕌𝕄𝕄𝕐 ℂℍ𝕆𝔻 𝔻𝔼ℕ𝔾𝔼\ᑎ 𝔾𝔸𝔻ℍ𝔸 𝕂ℍ𝕆𝔻 𝔻𝔼ℕ𝔾𝔼 ℝ𝔼 𝕄𝔸𝔸𝔻𝔸ℝℂℍ𝕆𝔻\ᑎ🤣🤤🤞☺️🥱🤤",
    "ᴛᴜ ʙᴏʟᴇɢᴀ ʙᴀᴀᴘ ᴋᴇ sᴀᴀᴍɴᴇ\ᑎᴛᴇʀɪ ᴍᴀᴀ ᴋᴀ ʀᴀᴘᴇ ᴋʀᴜ ᴍᴀᴀ ᴋᴇ ʟᴏᴡᴅᴇ\ᑎ🖕🖕🖕🖕🖕",
    "TᗴᖇI ᗰᗩᗩ ᗷᗴᕼᗩᑎ ᗪᗴᗴᑭᗩK😆ᑭᗴᒪᗴ\ᑎᗰᗩᗩ Kᗴ ᒪOᗯᗪᗴ\ᑎ😘😜🤓🤓🤓",
    "Tᑌᑌ ᒪEEGᗩᗩ ᕼᑌᗰSE ᑭᗩᑎGᗩ😋\ᑎSᗩᗩᒪE ᗪEEᑭᗩK😈 ᗩᑌᖇ ᑭIKᗩᑕᕼᑌ 🤓 ᑭEᒪEᑎGE TᑌᒍᕼE KᖇKE ᑎᗩᑎGᗩ\ᑎ🤩🤩😂😂😂🤣",
    "ᗩᗷᗷᗷᗷᗷᗷEEEE😆😆😆ᖇᖇᖇᖇᖇᖇᖇᑎᑎᗩᗩᗩᗪᗪᗪᗪᗪᗪᗪᗪII\ᑎ🤣🤣🤣ᗰᗰᗩᗩᗩᗩ😥😥KKEEEEE😃\ᑎᗷᗷᗷᗷᗷᗷᗷᗩᑕᑕᑕᑕᕼᕼᕼᕼEEEEEEEEEEE👅👅👅👅👅",
    "𝐀𝐁𝐄 𝐆𝐀𝐋𝐈 𝐆𝐀𝐋𝐈 𝐌𝐄𝐈𝐍 𝐂𝐇𝐀𝐋𝐀😝\ᑎ𝐆𝐀𝐋𝐈 𝐌𝐄𝐈𝐍 𝐌𝐈𝐋𝐀 𝐉𝐇𝐎𝐏𝐃𝐀🙈🤟\ᑎ𝐓𝐔 𝐀𝐔𝐑 𝐓𝐄𝐑𝐈 𝐌𝐀𝐀 𝐁𝐄𝐇𝐀𝐍 𝐊𝐀 𝐌𝐀𝐀𝐑𝐄 𝐇𝐔𝐌 𝐁𝐇𝐎𝐒𝐃𝐀\ᑎ😂🖕🤤🤞",
    "𝐄𝐊 𝐃𝐈𝐍 𝐌𝐀𝐑 𝐉𝐀𝐘𝐄𝐆𝐀 𝐊𝐔𝐓𝐓𝐄 𝐊𝐈 𝐌𝐀𝐔𝐓🥱\ᑎ𝐉𝐀𝐆 𝐌𝐄𝐈𝐍 𝐒𝐀𝐁 𝐊𝐀𝐇𝐄𝐍𝐆𝐄 𝐌𝐀𝐑 𝐆𝐘𝐀 𝐌𝐀𝐀𝐃𝐀𝐑𝐂𝐇𝐎𝐃\ᑎ😋🤣🤣🤣🤣",
    "ᑭᗩKᗩᗪ ᑭᗩKᗩᗪ Տᑭᗴᗴᗪ ᑭᗩKᗩᗪ😒😒\ᑎᗰᗩᗩ Kᗴ ᒪOᗯᗪᗴ ᖇᗩᑎᗪI Kᗴ ᑭIᒪᒪᗴ\ᑎ😤😤",
    "𝗔𝗔𝗕𝗘𝗘 𝗠𝗔𝗔𝗗𝗔𝗥𝗖𝗛𝗢𝗗 𝗣𝗔𝗔𝗔𝗡𝗜 𝗞𝗨𝗠 𝗛𝗔𝗜 𝗠𝗔𝗧𝗞𝗘 𝗠𝗘𝗜𝗡😖😖\ᑎ𝗛𝗔𝗠𝗔𝗔𝗥𝗘 𝗦𝗔𝗔𝗧𝗛 𝗦𝗔𝗔𝗧𝗛 𝗣𝗜𝗞𝗔𝗖𝗛𝗨 𝗔𝗨𝗥 𝗗𝗘𝗘𝗣𝗔𝗞 𝗕𝗛𝗜 𝗧𝗘𝗥𝗜 𝗚𝗔𝗔𝗡𝗗 𝗠𝗔𝗔𝗥𝗘 𝗝𝗛𝗔𝗧𝗞𝗘 𝗠𝗘𝗜𝗡\ᑎ😋😋😝😝😘😘😘😘🤟🤟",
    "🇦 🇧 🇪 \ᑎ🅴🅺\ᑎ🅳🅾️\ᑎ🆃🅴🅴🅽\ᑎ🅲🅷🅰️🅰️🆁\ᑎ🇹 🇪 🇷 🇮    🇲 🇦 🇦    🇰 🇮    🇨 🇭 🇺 🇹 \ᑎ🇧 🇴 🇭 🇺 🇹    🇴 🇵    🇭 🇦 🇮    🇾 🇷 \ᑎ😙😙😙😛😝😋😜😇🤟🤞",
    "𝘼𝘽𝙀𝙀 𝘼𝘼𝘼𝙂𝙀𝙀 𝙆𝙐𝘼𝘼 𝙋𝙀𝙀𝙀𝘾𝙃𝙀 𝙆𝙃𝘼𝘼𝙔𝙄🥱☺️\ᑎ𝙏𝙀𝙍𝙄 𝙏𝙊 𝙈𝙐𝙈𝙈𝙔 𝘾𝙃𝙐𝙐𝘿 𝙂𝙔𝙄𝙄 𝙈𝙀𝙍𝙀 𝘽𝙃𝘼𝙄𝙄\ᑎ😎🖕🖕😂😜🤤",
    "ᗷᗩᗩᑭ SE ᒪᗩᗪEGᗩ TO\ᑎᗰᑌᗰᗰY ᕼI ᑕᕼᑌᗪEGI ᑎᗩᗩ ᖇᗩᑎᗪI ᗰE ᑭIᒪᒪE🙄🤤🥴🥴\ᑎTᑌ ᗷOᒪEGᗩ ᗷᗩᗩᑭ KE SᗩᗩᗰᑎE ᗰᗩᗩᗪᗩᖇᑕᕼOᗪ\ᑎ😒😏🤬🤬🥵🥵",
    "𝖢𝖧𝖠ᕼE ᕼO ᑭᑌᑎITᕼ😒ᑕᕼᗩᕼE ᕼO Tᕼᗩᑭᗩ🙄\ᑎSᗩᗩᒪE ᗪEEᑭᗩK ᗩᑌᖇ ᑭIKᗩᑕᕼᑌ KO ᑕᕼOᖇ KE\ᑎ KᗩᗷᕼI ᕼᑌᗰE ᗷᕼI ᗷOᒪᗪO ᑭᗩᑭᗩ\ᑎ😤😤😤🥴🥴🥴🥴",
    "KᗩᗩᒪI ᑕᕼᑌT KE SᗩᖴEᗪ ᒍᕼᗩᗩᑎT…",
    "ᗩᗷᒪᗩ ᑎᗩᗩᖇI, TEᖇE ᗷᗩᗷᒪE ᗷᕼᗩᗩᖇI… ",
    "GOTE KITᑎE ᗷᕼI ᗷᗩᗪEY ᕼO, ᒪᑌᑎᗪ KE ᑎIᑕᕼE ᕼI ᖇEᕼTEIᑎ ᕼᗩIᑎ… ",
    "ᗰᗩᗪᗩᖇᑕᕼOᗪ TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰE GᕼᑌTKᗩ KᕼᗩᗩKE TᕼOOK ᗪᑌᑎGᗩ 🤣🤣",
    "TEᖇE ᗷEᕼEᑎ K ᑕᕼᑌT ᗰE ᑕᕼᗩKᑌ ᗪᗩᗩᒪ Kᗩᖇ ᑕᕼᑌT Kᗩ KᕼOOᑎ Kᗩᖇ ᗪᑌGᗩ",
    "TEᖇI ᐯᗩᕼEEᑎ ᑎᕼI ᕼᗩI KYᗩ? 9 ᗰᗩᕼIᑎE ᖇᑌK SᗩGI ᐯᗩᕼEEᑎ ᗪETᗩ ᕼᑌ 🤣🤣🤩",
    "TEᖇI ᗰᗩᗩ K ᗷᕼOSᗪE ᗰE ᗩEᖇOᑭᒪᗩᑎEᑭᗩᖇK KᗩᖇKE ᑌᗪᗩᗩᑎ ᗷᕼᗩᖇ ᗪᑌGᗩ ✈️🛫",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰE SᑌTᒪI ᗷOᗰᗷ ᖴOᗪ ᗪᑌᑎGᗩ TEᖇI ᗰᗩᗩ KI ᒍᕼᗩᗩTE ᒍᗩᒪ KE KᕼᗩᗩK ᕼO ᒍᗩYEGI💣",
    "TEᖇI ᗰᗩᗩKI ᑕᕼᑌT ᗰE SᑕOOTEᖇ ᗪᗩᗩᒪ ᗪᑌGᗩ👅",
    "TEᖇE ᗷEᕼEᑎ K ᑕᕼᑌT ᗰE ᑕᕼᗩKᑌ ᗪᗩᗩᒪ Kᗩᖇ ᑕᕼᑌT Kᗩ KᕼOOᑎ Kᗩᖇ ᗪᑌGᗩ",
    "TEᖇE ᗷEᕼEᑎ K ᑕᕼᑌT ᗰE ᑕᕼᗩKᑌ ᗪᗩᗩᒪ Kᗩᖇ ᑕᕼᑌT Kᗩ KᕼOOᑎ Kᗩᖇ ᗪᑌGᗩ",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT KᗩKTE 🤱 GᗩᒪI KE KᑌTTO 🦮 ᗰE ᗷᗩᗩT ᗪᑌᑎGᗩ ᑭᕼIᖇ 🍞 ᗷᖇEᗩᗪ KI Tᗩᖇᕼ KᕼᗩYEᑎGE ᗯO TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT",
    "ᗪᑌᗪᕼ ᕼIᒪᗩᗩᑌᑎGᗩ TEᖇI ᐯᗩᕼEEᑎ KE ᑌᑭᖇ ᑎIᑕᕼE 🆙🆒😙",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰE ✋ ᕼᗩTTᕼ ᗪᗩᒪKE 👶 ᗷᗩᑕᑕᕼE ᑎIKᗩᒪ ᗪᑌᑎGᗩ 😍",
    "TEᖇI ᗷEᕼᑎ KI ᑕᕼᑌT ᗰE KEᒪE KE ᑕᕼIᒪKE 🍌🍌😍",
    "TEᖇI ᗷᕼEᑎ KI ᑕᕼᑌT ᗰE ᑌSEᖇᗷOT ᒪᗩGᗩᗩᑌᑎGᗩ SᗩSTE Sᑭᗩᗰ KE ᑕᕼOᗪE",
    "TEᖇI ᐯᗩᕼEEᑎ ᗪᕼᗩᑎᗪᕼE ᐯᗩᗩᒪI 😋😛",
    "TEᖇI ᗰᗩᗩ KE ᗷᕼOSᗪE ᗰE ᗩᑕ ᒪᗩGᗩ ᗪᑌᑎGᗩ SᗩᗩᖇI GᗩᖇᗰI ᑎIKᗩᒪ ᒍᗩᗩYEGI",
    "TEᖇI ᐯᗩᕼEEᑎ KO ᕼOᖇᒪIᑕKS ᑭEEᒪᗩᑌᑎGᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ😚",
    "TEᖇI ᗰᗩᗩ KI Gᗩᗩᑎᗪ ᗰE SᗩᖇIYᗩ ᗪᗩᗩᒪ ᗪᑌᑎGᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ ᑌSI SᗩᖇIYE ᑭᖇ TᗩᑎG KE ᗷᗩᑕᕼE ᑭᗩIᗪᗩ ᕼOᑎGE 😱😱",
    "TEᖇI ᗰᗩᗩ KO KOᒪKᗩTᗩ ᐯᗩᗩᒪE ᒍITᑌ ᗷᕼᗩIYᗩ Kᗩ ᒪᑌᑎᗪ ᗰᑌᗷᗩᖇᗩK 🤩🤩",
    "TEᖇI ᗰᑌᗰᗰY KI ᖴᗩᑎTᗩSY ᕼᑌ ᒪᗩᗯᗪE, Tᑌ ᗩᑭᑎI ᗷᕼEᑎ KO Sᗰᗷᕼᗩᗩᒪ 😈😈",
    "TEᖇᗩ ᑭEᕼᒪᗩ ᗷᗩᗩᑭ ᕼᑌ ᗰᗩᗪᗩᖇᑕᕼOᗪ ",
    "TEᖇI ᐯᗩᕼEEᑎ KE ᗷᕼOSᗪE ᗰE ᙭ᐯIᗪEOS.ᑕOᗰ ᑕᕼᗩᒪᗩ KE ᗰᑌTᕼ ᗰᗩᗩᖇᑌᑎGᗩ 🤡😹",
    "TEᖇI ᗰᗩᗩ Kᗩ GᖇOᑌᑭ ᐯᗩᗩᒪOᑎ SᗩᗩTᕼ ᗰIᒪKE GᗩᑎG ᗷᗩᑎG KᖇᑌᑎGᗩ🙌🏻☠️ ",
    "TEᖇI ITEᗰ KI Gᗩᗩᑎᗪ ᗰE ᒪᑌᑎᗪ ᗪᗩᗩᒪKE,TEᖇE ᒍᗩISᗩ EK Oᖇ ᑎIKᗩᗩᒪ ᗪᑌᑎGᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ🤘🏻🙌🏻☠️ ",
    "ᗩᑌKᗩᗩT ᗰE ᖇEᕼ ᐯᖇᑎᗩ Gᗩᗩᑎᗪ ᗰE ᗪᗩᑎᗪᗩ ᗪᗩᗩᒪ KE ᗰᑌᕼ SE ᑎIKᗩᗩᒪ ᗪᑌᑎGᗩ SᕼᗩᖇIᖇ ᗷᕼI ᗪᗩᑎᗪE ᒍESᗩ ᗪIKᕼEGᗩ 🙄🤭🤭",
    "TEᖇI ᗰᑌᗰᗰY KE SᗩᗩTᕼ ᒪᑌᗪO KᕼEᒪTE KᕼEᒪTE ᑌSKE ᗰᑌᕼ ᗰE ᗩᑭᑎᗩ ᒪOᗪᗩ ᗪE ᗪᑌᑎGᗩ☝🏻☝🏻😬",
    "TEᖇI ᐯᗩᕼEEᑎ KO ᗩᑭᑎE ᒪᑌᑎᗪ ᑭᖇ ITᑎᗩ ᒍᕼᑌᒪᗩᗩᑌᑎGᗩ KI ᒍᕼᑌᒪTE ᒍᕼᑌᒪTE ᕼI ᗷᗩᑕᕼᗩ ᑭᗩIᗪᗩ Kᖇ ᗪEGI👀👯 ",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰEI ᗷᗩTTEᖇY ᒪᗩGᗩ KE ᑭOᗯEᖇᗷᗩᑎK ᗷᗩᑎᗩ ᗪᑌᑎGᗩ 🔋 🔥🤩",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰEI ᑕ++ STᖇIᑎG EᑎᑕᖇYᑭTIOᑎ ᒪᗩGᗩ ᗪᑌᑎGᗩ ᗷᗩᕼTI ᕼᑌYI ᑕᕼᑌT ᖇᑌK ᒍᗩYEGIIII😈🔥😍",
    "TEᖇI ᗰᗩᗩ KE Gᗩᗩᑎᗪ ᗰEI ᒍᕼᗩᗩᗪᑌ ᗪᗩᒪ KE ᗰOᖇ 🦚 ᗷᗩᑎᗩ ᗪᑌᑎGᗩᗩ 🤩🥵😱",
    "TEᖇI ᑕᕼᑌT KI ᑕᕼᑌT ᗰEI SᕼOᑌᒪᗪEᖇIᑎG Kᗩᖇ ᗪᑌᑎGᗩᗩ ᕼIᒪᗩTE ᕼᑌYE ᗷᕼI ᗪᗩᖇᗪ ᕼOGᗩᗩᗩ😱🤮👺",
    "TEᖇI ᗰᗩᗩ KO ᖇEᗪI ᑭE ᗷᗩITᕼᗩᒪ KE ᑌSSE ᑌSKI ᑕᕼᑌT ᗷIᒪᗯᗩᑌᑎGᗩᗩ 💰 😵🤩",
    "ᗷᕼOSᗪIKE TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰEI 4 ᕼOᒪE ᕼᗩI ᑌᑎᗰE ᗰSEᗩᒪ ᒪᗩGᗩ ᗷᗩᕼᑌT ᗷᗩᕼETI ᕼᗩI ᗷᕼOᖴᗪIKE👊🤮🤢🤢",
    "TEᖇI ᗷᗩᕼEᑎ KI ᑕᕼᑌT ᗰEI ᗷᗩᖇGᗩᗪ Kᗩ ᑭEᗪ ᑌGᗩ ᗪᑌᑎGᗩᗩ ᑕOᖇOᑎᗩ ᗰEI Sᗩᗷ O᙭YGEᑎ ᒪEKᗩᖇ ᒍᗩYEᑎGE🤢🤩🥳",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰEI SᑌᗪO ᒪᗩGᗩ KE ᗷIGSᑭᗩᗰ ᒪᗩGᗩ KE 9999 ᖴᑌᑕK ᒪᗩGᗩᗩ ᗪᑌ 🤩🥳🔥",
    "TEᖇI ᐯᗩᕼEᑎ KE ᗷᕼOSᗪIKE ᗰEI ᗷESᗩᑎ KE ᒪᗩᗪᗪᑌ ᗷᕼᗩᖇ ᗪᑌᑎGᗩ🤩🥳🔥😈",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT KᕼOᗪ KE ᑌSᗰE ᑕYᒪIᑎᗪEᖇ ⛽️ ᖴIT KᗩᖇKE ᑌSᗰEE ᗪᗩᒪ ᗰᗩKᕼᗩᑎI ᗷᗩᑎᗩᑌᑎGᗩᗩᗩ🤩👊🔥",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰEI SᕼEESᕼᗩ ᗪᗩᒪ ᗪᑌᑎGᗩᗩᗩ ᗩᑌᖇ ᑕᕼᗩᑌᖇᗩᕼE ᑭE TᗩᗩᑎG ᗪᑌᑎGᗩ ᗷᕼOSᗪIKE😈😱🤩",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰEI ᑕᖇEᗪIT ᑕᗩᖇᗪ ᗪᗩᒪ KE ᗩGE SE 500 KE KᗩᗩᖇE KᗩᗩᖇE ᑎOTE ᑎIKᗩᒪᑌᑎGᗩᗩ ᗷᕼOSᗪIKE💰💰🤩",
    "TEᖇI ᗰᗩᗩ KE SᗩTᕼ Sᑌᗩᖇ Kᗩ SE᙭ Kᗩᖇᗯᗩ ᗪᑌᑎGᗩᗩ EK SᗩTᕼ 6-6 ᗷᗩᑕᕼE ᗪEGI💰🔥😱",
    "TEᖇI ᗷᗩᕼEᑎ KI ᑕᕼᑌT ᗰEI ᗩᑭᑭᒪE Kᗩ 18ᗯ ᗯᗩᒪᗩ ᑕᕼᗩᖇGEᖇ 🔥🤩",
    "TEᖇI ᗷᗩᕼEᑎ KI Gᗩᗩᑎᗪ ᗰEI OᑎEᑭᒪᑌS Kᗩ ᗯᖇᗩᑭ ᑕᕼᗩᖇGEᖇ 30ᗯ ᕼIGᕼ ᑭOᗯEᖇ 💥😂😎",
    "TEᖇI ᗷᗩᕼEᑎ KI ᑕᕼᑌT KO ᗩᗰᗩᘔOᑎ SE OᖇᗪEᖇ KᗩᖇᑌᑎGᗩ 10 ᖇs ᗰEI ᗩᑌᖇ ᖴᒪIᑭKᗩᖇT ᑭE 20 ᖇS ᗰEI ᗷEᑕᕼ ᗪᑌᑎGᗩ🤮👿😈🤖",
    "TEᖇI ᗰᗩᗩ KI ᗷᗩᗪI ᗷᕼᑌᑎᗪ ᗰE ᘔOᗰᗩTO ᗪᗩᒪ KE SᑌᗷᗯᗩY Kᗩ ᗷᖴᖴ ᐯEG Sᑌᗷ ᑕOᗰᗷO [15ᑕᗰ , 16 IᑎᑕᕼEs ] OᖇᗪEᖇ ᑕOᗪ KᖇᐯᗩᑌᑎGᗩ Oᖇ TEᖇI ᗰᗩᗩ ᒍᗩᗷ ᗪIᒪIᐯEᖇY ᗪEᑎE ᗩYEGI Tᗩᗷ ᑌSᑭE ᒍᗩᗩᗪᑌ KᖇᑌᑎGᗩ Oᖇ ᖴIᖇ 9 ᗰOᑎTᕼ ᗷᗩᗩᗪ ᐯO EK Oᖇ ᖴᖇEE ᗪIᒪIᐯEᖇY ᗪEGI🙀👍🥳🔥",
    "TEᖇI ᗷᕼEᑎ KI ᑕᕼᑌT KᗩᗩᒪI🙁🤣💥",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰE ᑕᕼᗩᑎGES ᑕOᗰᗰIT KᖇᑌGᗩ ᖴIᖇ TEᖇI ᗷᕼEEᑎ KI ᑕᕼᑌT ᗩᑌTOᗰᗩTIᑕᗩᒪᒪY ᑌᑭᗪᗩTE ᕼOᒍᗩᗩYEGI🤖🙏🤔",
    "TEᖇI ᗰᗩᑌSI KE ᗷᕼOSᗪE ᗰEI IᑎᗪIᗩᑎ ᖇᗩIᒪᗯᗩY 🚂💥😂",
    "Tᑌ TEᖇI ᗷᗩᕼEᑎ TEᖇᗩ Kᕼᗩᑎᗪᗩᑎ Sᗩᗷ ᗷᗩᕼEᑎ KE ᒪᗩᗯᗪE ᖇᗩᑎᗪI ᕼᗩI ᖇᗩᑎᗪI 🤢✅🔥",
    "TEᖇI ᗷᗩᕼEᑎ KI ᑕᕼᑌT ᗰEI IOᑎIᑕ ᗷOᑎᗪ ᗷᗩᑎᗩ KE ᐯIᖇGIᑎITY ᒪOOSE Kᗩᖇᗯᗩ ᗪᑌᑎGᗩ ᑌSKI 📚 😎🤩",
    "TEᖇI ᖇᗩᑎᗪI ᗰᗩᗩ SE ᑭᑌᑕᕼᑎᗩ ᗷᗩᗩᑭ Kᗩ ᑎᗩᗩᗰ ᗷᗩᕼEᑎ KE ᒪOᗪEEEEE 🤩🥳😳",
    "Tᑌ ᗩᑌᖇ TEᖇI ᗰᗩᗩ ᗪOᑎO KI ᗷᕼOSᗪE ᗰEI ᗰETᖇO ᑕᕼᗩᒪᗯᗩ ᗪᑌᑎGᗩ ᗰᗩᗪᗩᖇ᙭ᕼOᗪ 🚇🤩😱🥶",
    "TEᖇI ᗰᗩᗩ KO ITᑎᗩ ᑕᕼOᗪᑌᑎGᗩ TEᖇᗩ ᗷᗩᗩᑭ ᗷᕼI ᑌSKO ᑭᗩᕼᑕᕼᗩᑎᗩᑎE SE ᗰᗩᑎᗩ Kᗩᖇ ᗪEGᗩ😂👿🤩",
    "TEᖇI ᗷᗩᕼEᑎ KE ᗷᕼOSᗪE ᗰEI ᕼᗩIᖇ ᗪᖇYEᖇ ᑕᕼᗩᒪᗩ ᗪᑌᑎGᗩᗩ💥🔥🔥",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰEI TEᒪEGᖇᗩᗰ KI SᗩᖇI ᖇᗩᑎᗪIYOᑎ Kᗩ ᖇᗩᑎᗪI Kᕼᗩᑎᗩ KᕼOᒪ ᗪᑌᑎGᗩᗩ👿🤮😎",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗩᒪE᙭ᗩ ᗪᗩᒪ KEE ᗪᒍ ᗷᗩᒍᗩᑌᑎGᗩᗩᗩ 🎶 ⬆️🤩💥",
    "TEᖇI ᗰᗩᗩ KE ᗷᕼOSᗪE ᗰEI GITᕼᑌᗷ ᗪᗩᒪ KE ᗩᑭᑎᗩ ᗷOT ᕼOST KᗩᖇᑌᑎGᗩᗩ 🤩👊👤😍",
    "TEᖇI ᗷᗩᕼEᑎ Kᗩ ᐯᑭS ᗷᗩᑎᗩ KE 24*7 ᗷᗩSᕼ ᑕᕼᑌᗪᗩI ᑕOᗰᗰᗩᑎᗪ ᗪE ᗪᑌᑎGᗩᗩ 🤩💥🔥🔥",
    "TEᖇI ᗰᑌᗰᗰY KI ᑕᕼᑌT ᗰEI TEᖇE ᒪᗩᑎᗪ KO ᗪᗩᒪ KE KᗩᗩT ᗪᑌᑎGᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ 🔪😂🔥",
    "Sᑌᑎ TEᖇI ᗰᗩᗩ Kᗩ ᗷᕼOSᗪᗩ ᗩᑌᖇ TEᖇI ᗷᗩᕼEᑎ Kᗩ ᗷᕼI ᗷᕼOSᗪᗩ 👿😎👊",
    "TᑌᒍᕼE ᗪEKᕼ KE TEᖇI ᖇᗩᑎᗪI ᗷᗩᕼEᑎ ᑭE TᗩᖇᗩS ᗩTᗩ ᕼᗩI ᗰᑌᒍᕼE ᗷᗩᕼEᑎ KE ᒪOᗪEEEE 👿💥🤩🔥",
    "Sᑌᑎ ᗰᗩᗪᗩᖇᑕᕼOᗪ ᒍYᗩᗪᗩ ᑎᗩ ᑌᑕᕼᗩᒪ ᗰᗩᗩ ᑕᕼOᗪ ᗪEᑎGE EK ᗰIᑎ ᗰEI ✅🤣🔥🤩",
    "ᗩᑭᑎI ᗩᗰᗰᗩ SE ᑭᑌᑕᕼᑎᗩ ᑌSKO ᑌS KᗩᗩᒪI ᖇᗩᗩT ᗰEI Kᗩᑌᑎ ᑕᕼOᗪᑎEE ᗩYᗩ Tᕼᗩᗩᗩ! TEᖇE IS ᑭᗩᑭᗩ Kᗩ ᑎᗩᗩᗰ ᒪEGI 😂👿😳",
    "TOᕼᗩᖇ ᗷᗩᕼIᑎ ᑕᕼOᗪᑌ ᗷᗷᗩᕼEᑎ KE ᒪᗩᗯᗪE ᑌSᗰE ᗰITTI ᗪᗩᒪ KE ᑕEᗰEᑎT SE ᗷᕼᗩᖇ ᗪᑌ 🏠🤢🤩💥",
    "TᑌᒍᕼE ᗩᗷ TᗩK ᑎᗩᕼI Sᗰᒍᕼ ᗩYᗩ KI ᗰᗩI ᕼI ᕼᑌ TᑌᒍᕼE ᑭᗩIᗪᗩ KᗩᖇᑎE ᗯᗩᒪᗩ ᗷᕼOSᗪIKEE ᗩᑭᑎI ᗰᗩᗩ SE ᑭᑌᑕᕼ ᖇᗩᑎᗪI KE ᗷᗩᑕᕼEEEE 🤩👊👤😍",
    "TEᖇI ᗰᗩᗩ KE ᗷᕼOSᗪE ᗰEI SᑭOTIᖴY ᗪᗩᒪ KE ᒪOᖴI ᗷᗩᒍᗩᑌᑎGᗩ ᗪIᑎ ᗷᕼᗩᖇ 😍🎶🎶💥",
    "TEᖇI ᗰᗩᗩ Kᗩ ᑎᗩYᗩ ᖇᗩᑎᗪI Kᕼᗩᑎᗩ KᕼOᒪᑌᑎGᗩ ᑕᕼIᑎTᗩ ᗰᗩT Kᗩᖇ 👊🤣🤣😳",
    "TEᖇᗩ ᗷᗩᗩᑭ ᕼᑌ ᗷᕼOSᗪIKE TEᖇI ᗰᗩᗩ KO ᖇᗩᑎᗪI KᕼᗩᑎE ᑭE ᑕᕼᑌᗪᗯᗩ KE ᑌS ᑭᗩISE KI ᗪᗩᗩᖇᑌ ᑭEETᗩ ᕼᑌ 🍷🤩🔥",
    "TEᖇI ᗷᗩᕼEᑎ KI ᑕᕼᑌT ᗰEI ᗩᑭᑎᗩ ᗷᗩᗪᗩ Sᗩ ᒪOᗪᗩ GᕼᑌSSᗩ ᗪᑌᑎGᗩᗩ Kᗩᒪᒪᗩᗩᑭ KE ᗰᗩᖇ ᒍᗩYEGI 🤩😳😳🔥",
    "TOᕼᗩᖇ ᗰᑌᗰᗰY KI ᑕᕼᑌT ᗰEI ᑭᑌᖇI KI ᑭᑌᖇI KIᑎGᖴISᕼEᖇ KI ᗷOTTᒪE ᗪᗩᒪ KE TOᗪ ᗪᑌᑎGᗩ ᗩᑎᗪEᖇ ᕼI 😱😂🤩",
    "TEᖇI ᗰᗩᗩ KO ITᑎᗩ ᑕᕼOᗪᑌᑎGᗩ KI SᗩᑭᑎE ᗰEI ᗷᕼI ᗰEᖇI ᑕᕼᑌᗪᗩI Yᗩᗩᗪ KᗩᖇEGI ᖇᗩᑎᗪI 🥳😍👊💥",
    "TEᖇI ᗰᑌᗰᗰY ᗩᑌᖇ ᗷᗩᕼEᑎ KO ᗪᗩᑌᗪᗩ ᗪᗩᑌᗪᗩ ᑎE ᑕᕼOᗪᑌᑎGᗩ ᑌᑎKE ᑎO ᗷOᒪᑎE ᑭE ᗷᕼI ᒪᗩᑎᗪ GᕼᑌSᗩ ᗪᑌᑎGᗩ ᗩᑎᗪEᖇ TᗩK 😎😎🤣🔥",
    "TEᖇI ᗰᑌᗰᗰY KI ᑕᕼᑌT KO OᑎᒪIᑎE Oᒪ᙭ ᑭE ᗷEᑕᕼᑌᑎGᗩ ᗩᑌᖇ ᑭᗩISE SE TEᖇI ᗷᗩᕼEᑎ Kᗩ KOTᕼᗩ KᕼOᒪ ᗪᑌᑎGᗩ 😎🤩😝😍",
    "TEᖇI ᗰᗩᗩ KE ᗷᕼOSᗪᗩ ITᑎᗩ ᑕᕼOᗪᑌᑎGᗩ KI Tᑌ ᑕᗩᕼ KE ᗷᕼI ᗯO ᗰᗩST ᑕᕼᑌᗪᗩI SE ᗪᑌᖇ ᑎᕼI ᒍᗩ ᑭᗩYEGᗩᗩ 😏😏🤩😍",
    "Sᑌᑎ ᗷE ᖇᗩᑎᗪI KI ᗩᑌᒪᗩᗩᗪ Tᑌ ᗩᑭᑎI ᗷᗩᕼEᑎ SE SEEKᕼ Kᑌᑕᕼ KᗩISE Gᗩᗩᑎᗪ ᗰᗩᖇᗯᗩTE ᕼᗩI😏🤬🔥💥",
    "TEᖇI ᗰᗩᗩ Kᗩ Yᗩᗩᖇ ᕼᑌ ᗰEI ᗩᑌᖇ TEᖇI ᗷᗩᕼEᑎ Kᗩ ᑭYᗩᗩᖇ ᕼᑌ ᗰEI ᗩᒍᗩ ᗰEᖇᗩ ᒪᗩᑎᗪ ᑕᕼOOS ᒪE 🤩🤣💥",
    "ᗰᗩᗪᗩᖇᑕᕼOᗪ",
    "ᑭᕼᗩTEᒪE ᑎIᖇOᗪᕼ KE ᑎᗩTIᒍE!",
    "TEᖇI Gᗩᗩᑎᗪ ᗰEIᑎ KᑌTTE Kᗩ ᒪᑌᑎᗪ… ",
    "ᑕᕼᑌT KE ᑭᗩsIᑎE ᗰEIᑎ TᗩᒪᗩY ᕼᑌE ᗷᕼᗩᒍIYE…",
    "ᗷᕼOSᗪIKE",
    "ᒪᗩᗩᗩᗯEEE KE ᗷᗩᗩᗩᗩᗩᒪ",
    "ᗰᗩᗩᗩᗩᖇ KI ᒍᕼᗩᗩᗩᗩT KE ᗷᗷᗷᗷᗷᗩᗩᗩᗩᗩᒪᒪᒪᒪᒪ",
    "ᗰᗩᗪᖇᑕᕼOᗪ..",
    "TEᖇI ᗰᗩ KI ᑕᕼᑌT..",
    "ᒪᗯᗪE KE ᗷᗩᗩᗩᒪᒪᒪ.",
    "ᗰᗩᑕᕼᗩᖇ KI ᒍᕼᗩᗩT KE ᗷᗩᗩᗩᒪᒪᒪᒪ",
    "TEᖇI ᗰᗩ KI ᑕᕼᑌT ᗰ ᗪᑌ Tᗩᑭᗩ Tᗩᑭ?",
    "TEᖇI ᗰᗩ Kᗩ ᗷᕼOSᗪᗩᗩ",
    "TEᖇI ᗷᕼᑎ SᗷSᗷE ᗷᗪI ᖇᗩᑎᗪI.",
    "TEᖇI ᗰᗩ OSSE ᗷᗩᗪI ᖇᗩᑎᗪᗪᗪᗪᗪ",
    "TEᖇᗩ ᗷᗩᗩᑭ ᑕᕼKᗩᗩᗩᗩ",
    "KITᑎI ᑕᕼOᗪᑌ TEᖇI ᗰᗩ ᗩᗷ Oᖇ..",
    "TEᖇI ᗰᗩ ᑕᕼOᗪ ᗪI ᕼᗰ ᑎE",
    "TEᖇI ᗰᗩ KE STᕼ ᖇEEᒪS ᗷᑎEGᗩ ᖇOᗩᗪ ᑭEE",
    "TEᖇI ᗰᗩ KI ᑕᕼᑌT EK ᗪᗩᗰ TOᑭ SE᙭Y",
    "ᗰᗩᒪᑌᗰ ᑎᗩ ᑭᕼᖇ KESE ᒪETᗩ ᕼᑌ ᗰ TEᖇI ᗰᗩ KI ᑕᕼᑌT Tᗩᑭᗩ Tᗩᑭᑭᑭᑭᑭ",
    "ᒪᑌᑎᗪ KE ᑕᕼOᗪE Tᑌ KEᖇEGᗩ TYᑭIᑎ",
    "SᑭEEᗪ ᑭKᗪ ᒪᗯᗪEEEE",
    "ᗷᗩᗩᑭ KI SᑭEEᗪ ᗰTᑕᕼ Kᖇᖇᖇ",
    "ᒪᗯᗪEEE",
    "ᑭᗩᑭᗩ KI SᑭEEᗪ ᗰTᑕᕼ ᑎᕼI ᕼO ᖇᕼI KYᗩ",
    "ᗩᒪE ᗩᒪE ᗰEᒪᗩ ᗷᑕᕼᗩᗩᗩᗩ",
    "ᑕᕼᑌᗪ GYᗩ ᑭᗩᑭᗩ SEEE",
    "KISᗩᑎ KO KᕼOᗪᑎᗩ Oᖇ",
    "SᗩᒪE ᖇᗩᑭEKᒪ KᖇᗪKᗩ TEᖇᗩ",
    "ᕼᗩᕼᗩᕼᗩᗩᗩᗩᗩ",
    "KIᗪSSSS",
    "TEᖇI ᗰᗩ ᑕᕼᑌᗪ GYI ᗩᗷ ᖴᖇᗩᖇ ᗰT ᕼOᑎᗩ",
    "YE ᒪᗪᑎGE ᗷᗩᑭᑭ SE",
    "KIᗪSSS ᖴᖇᗩᖇ ᕼᗩᕼᗩᕼᕼ",
    "ᗷᕼEᑎ KE ᒪᗯᗪE Sᕼᖇᗰ Kᖇ",
    "KITᑎI GᒪIYᗩ ᑭᗪᗯEGᗩ ᗩᑭᑎI ᗰᗩ KO",
    "ᑎᗩᒪᒪEE",
    "Sᕼᖇᗰ Kᖇ",
    "ᗰEᖇE ᒪᑌᑎᗪ KE ᗷᗩᗩᗩᗩᗩᒪᒪᒪᒪᒪ",
    "KITᑎI GᒪIYᗩ ᑭᗪᗯYGᗩ ᗩᑭᑎI ᗰᗩ ᗷᕼEᑎ KO",
    "ᖇᑎᗪI KE ᒪᗪKEEEEEEEEE",
    "KIᗪSSSSSSSSSSSS",
    "ᗩᑭᑎI Gᗩᗩᑎᗪ ᗰEIᑎ ᗰᑌTᕼI ᗪᗩᗩᒪ",
    "ᗩᑭᑎI ᒪᑌᑎᗪ ᑕᕼOOs",
    "ᗩᑭᑎI ᗰᗩ KO ᒍᗩ ᑕᕼOOs",
    "ᗷᕼEᑎ KE ᒪᗩᑌᗪE",
    "ᗷᕼEᑎ KE TᗩKKE",
    "ᗩᗷᒪᗩ TEᖇᗩ Kᕼᗩᑎ ᗪᗩᑎ ᑕᕼOᗪᑎE KI ᗷᗩᖇIII",
    "ᗷETE TEᖇI ᗰᗩ SᗷSE ᗷᗪI ᖇᗩᑎᗪ",
    "ᒪᑌᑎᗪ KE ᗷᗩᗩᗩᒪ ᒍᕼᗩT KE ᑭISSSᑌᑌᑌᑌᑌᑌᑌ",
    "ᒪᑌᑎᗪ ᑭE ᒪTKIT ᗰᗩᗩᗩᒪᒪᒪᒪ KI ᗷOᑎᗪ ᕼ Tᑌᑌᑌ",
    "KᗩSᕼ OS ᗪIᑎ ᗰᑌTᕼ ᗰᖇKE SOᒍTᗩ ᗰ Tᑌᑎ ᑭᗩIᗪᗩ ᑎᗩ ᕼOTᗩᗩ",
    "GᒪTI KᖇᗪI Tᑌᒍᗯ ᑭᗩIᗪᗩ KᖇKE",
    "SᑭEEᗪ ᑭKᗪᗪᗪ",
    "Gᗩᗩᑎᗪ ᗰᗩIᑎ ᒪᗯᗪᗩ ᗪᗩᒪ ᒪE ᗩᑭᑎI ᗰEᖇᗩᗩᗩ",
    "Gᗩᗩᑎᗪ ᗰEIᑎ ᗷᗩᗰᗷᑌ ᗪEᗪᑌᑎGᗩᗩᗩᗩᗩᗩ",
    "Gᗩᑎᗪ ᖴTI KE ᗷᗩᒪKKK",
    "GOTE KITᑎE ᗷᕼI ᗷᗩᗪE ᕼO, ᒪᑌᑎᗪ KE ᑎIᑕᕼE ᕼI ᖇEᕼTE ᕼᗩI",
    "ᕼᗩᘔᗩᗩᖇ ᒪᑌᑎᗪ TEᖇI Gᗩᗩᑎᗪ ᗰᗩIᑎ",
    "ᒍᕼᗩᗩᑎT KE ᑭIssᑌ-",
    "TEᖇI ᗰᗩ KI KᗩᒪI ᑕᕼᑌT",
    "KᕼOTEY KI ᗩᑌᒪᗪᗩ",
    "KᑌTTE Kᗩ ᗩᗯᒪᗩT",
    "KᑌTTE KI ᒍᗩT",
    "KᑌTTE KE TᗩTTE",
    "TETI ᗰᗩ KI.ᑕᕼᑌT , TEᖇI ᗰᗩ ᖇᑎᗪIIIIIIIIIIIIIIIIIIII",
    "ᒪᗩᐯᗪE KE ᗷᗩᒪ",
    "ᗰᑌᕼ ᗰEI ᒪEᒪE",
    "ᒪᑌᑎᗪ KE ᑭᗩsIᑎE",
    "ᗰEᖇE ᒪᗯᗪE KE ᗷᗩᗩᗩᗩᗩᒪᒪᒪ",
    "ᕼᗩᕼᗩᕼᗩᗩᗩᗩᗩᗩ",
    "ᑕᕼᑌᗪ GYᗩᗩᗩᗩᗩ",
    "ᖇᗩᑎᗪI KᕼᗩᑎE KI ᑌᒪᗩᗪᗪᗪ",
    "SᗩᗪI ᕼᑌI Gᗩᗩᑎᗪ",
    "TEᖇI Gᗩᗩᑎᗪ ᗰᗩIᑎ KᑌTE Kᗩ ᒪᑌᑎᗪ",
    "TEᖇI ᗰᗩᗩ Kᗩ ᗷᕼOsᗪᗩ",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT",
    "TEᖇE Gᗩᗩᑎᗪ ᗰEIᑎ KEEᗪE ᑭᗩᗪᗩY",
    "ᑌᒪᒪᑌ KE ᑭᗩTᕼE",
    "Sᑌᑎᑎ ᗰᗩᗪEᖇᑕᕼOᗪ",
    "TEᖇI ᗰᗩᗩ Kᗩ ᗷᕼOSᗪᗩ",
    "ᗷEᕼEᑎ K ᒪᑌᑎᗪ",
    "TEᖇI ᗰᗩᗩ Kᗩ ᑕᕼᑌT KI ᑕᕼTᑎIIII",
    "ᗰEᖇᗩ ᒪᗩᗯᗪᗩ ᒪEᒪE Tᑌ ᗩGᗩᖇ ᑕᕼᗩIYE TOᕼ",
    "Gᗩᗩᑎᗪᑌ",
    "ᑕᕼᑌTIYᗩ",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᑭE ᒍᑕᗷ ᑕᕼᗩᗪᕼᗩᗩ ᗪᑌᑎGᗩ",
    "Sᗩᗰᒍᕼᗩᗩ ᒪᗩᗯᗪE",
    "Yᗩ ᗪᑌ TEᖇE Gᗩᗩᑎᗪ ᗰE Tᗩᑭᗩᗩ Tᗩᑭ��",
    "TEᖇI ᗷEᕼEᑎ ᗰEᖇᗩ ᖇOᘔ ᒪETI ᕼᗩI",
    "TEᖇI Gᖴ K SᗩᗩTᕼ ᗰᗰS ᗷᗩᑎᗩᗩ ᑕᕼᑌKᗩ ᕼᑌ���不�不",
    "Tᑌ ᑕᕼᑌTIYᗩ TEᖇᗩ Kᕼᗩᑎᗪᗩᗩᑎ ᑕᕼᑌTIYᗩ",
    "ᗩᑌᖇ KITᑎᗩ ᗷOᒪᑌ ᗷEY ᗰᗩᑎᑎ ᗷᕼᗩᖇ GᗩYᗩ ᗰEᖇᗩ�不",
    "TEᖇIIIIII ᗰᗩᗩᗩᗩ KI ᑕᕼᑌTTT ᗰE ᗩᗷᑕᗪ ᒪIKᕼ ᗪᑌᑎGᗩ ᗰᗩᗩ KE ᒪOᗪE",
    "TEᖇI ᗰᗩᗩ KO ᒪEKᗩᖇ ᗰᗩI ᖴᗩᖇᗩᖇ",
    "ᖇᗩᑎIᗪIII",
    "ᗷᗩᑕᕼEE",
    "ᑕᕼOᗪᑌ",
    "ᖇᗩᑎᗪI",
    "ᖇᗩᑎᗪI KE ᑭIᒪᒪE",
    "TEᖇIIIII ᗰᗩᗩᗩ KO ᗷᕼEᒍᒍᒍ",
    "TEᖇᗩᗩ ᗷᗩᗩᗩᗩᑭ ᕼᑌ",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰE ᕼᗩᗩT ᗪᗩᗩᒪᒪKE ᗷᕼᗩᗩG ᒍᗩᗩᑎᑌGᗩ",
    "TEᖇI ᗰᗩᗩ KO SᗩᖇᗩK ᑭE ᒪETᗩᗩ ᗪᑌᑎGᗩ",
    "TEᖇI ᗰᗩᗩ KO Gᗷ ᖇOᗩᗪ ᑭE ᒪEᒍᗩKE ᗷEᑕᕼ ᗪᑌᑎGᗩ",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰÉ KᗩᗩᒪI ᗰITᑕᕼ",
    "TEᖇI ᗰᗩᗩ SᗩSTI ᖇᗩᑎᗪI ᕼᗩI",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰE KᗩᗷᑌTᗩᖇ ᗪᗩᗩᒪ KE SOᑌᑭ ᗷᗩᑎᗩᑌᑎGᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ",
    "TEᖇI ᗰᗩᗩᗩ ᖇᗩᑎᗪI ᕼᗩI",
    "TEᖇI ᗰᗩᗩᗩ KI ᑕᕼᑌT ᗰE ᗪETOᒪ ᗪᗩᗩᒪ ᗪᑌᑎGᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ",
    "TEᖇI ᗰᗩᗩ Kᗩᗩᗩ ᗷᕼOSᗪᗩᗩ",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰE ᒪᗩᑭTOᑭ",
    "TEᖇI ᗰᗩᗩ ᖇᗩᑎᗪI ᕼᗩI",
    "TEᖇI ᗰᗩᗩ KO ᗷISTᗩᖇ ᑭE ᒪETᗩᗩKE ᑕᕼOᗪᑌᑎGᗩ",
    "TEᖇI ᗰᗩᗩ KO ᗩᗰEᖇIᑕᗩ GᕼᑌᗰᗩᗩᑌᑎGᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰE ᑎᗩᗩᖇIYᗩᒪ ᑭᕼOᖇ ᗪᑌᑎGᗩ",
    "TEᖇI ᗰᗩᗩ KE Gᗩᑎᗪ ᗰE ᗪETOᒪ ᗪᗩᗩᒪ ᗪᑌᑎGᗩ",
    "TEᖇI ᗰᗩᗩᗩ KO ᕼOᖇᒪIᑕKS ᑭIᒪᗩᑌᑎGᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ",
    "TEᖇI ᗰᗩᗩ KO SᗩᖇᗩK ᑭE ᒪETᗩᗩᗩ ᗪᑌᑎGᗩᗩᗩ",
    "TEᖇI ᗰᗩᗩ Kᗩᗩ ᗷᕼOSᗪᗩ",
    "ᗰEᖇᗩᗩᗩ ᒪᑌᑎᗪ ᑭᗩKᗩᗪ ᒪE ᗰᗩᗪᗩᖇᑕᕼOᗪ",
    "ᑕᕼᑌᑭ TEᖇI ᗰᗩᗩ ᗩKᗩᗩ ᗷᕼOSᗪᗩᗩ",
    "TEᖇIII ᗰᗩᗩ ᑕᕼᑌᖴ GEYII KYᗩᗩᗩ ᒪᗩᗯᗪEEE",
    "TEᖇIII ᗰᗩᗩ Kᗩᗩ ᗷᒍSOᗪᗩᗩᗩ",
    "ᗰᗩᗪᗩᖇ᙭ᕼOᗪᗪᗪ",
    "TEᖇIᑌᑌI ᗰᗩᗩᗩ Kᗩᗩ ᗷᕼSOᗪᗩᗩᗩ",
    "TEᖇIIIIII ᗷEᕼEᑎᑎᑎᑎ KO ᑕᕼOᗪᗪᗪᑌᑌᑌᑌ ᗰᗩᗪᗩᖇ᙭ᕼOᗪᗪᗪᗪ",
    "ᑎIKᗩᒪ ᗰᗩᗪᗩᖇᑕᕼOᗪ",
    "ᖇᗩᑎᗪI KE ᗷᗩᑕᕼE",
    "TEᖇᗩ ᗰᗩᗩ ᗰEᖇI ᖴᗩᑎ",
    "TEᖇI SE᙭Y ᗷᗩᕼEᑎ KI ᑕᕼᑌT Oᑭ",
    "TEᖇI ᗰᗩᗩ Kᗩᗩ ᗷᕼOSᗪᗩ ᗰEE ᗷᖇOᗯᑎ SᑌGᗩᖇ ᗪᗩᒪ KE ᑕᕼOᗪᑌ",
]

RRAID = [
    "TEᖇIII ᗩᗰᗰᗩ Kᗩ ᗷSᗪᗩ ᗰᗩI ᗷOᗰᗷ ᒪᗩGᗩKᖇ ᒍᒪᗩ ᗪᑌᑎGᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ💦🍆🍑😍",
    "ᗷSᗪK TEᖇII Gᗩᗩᑎᗪ ᖴᗩᗩᗪ ᗪᑌᑎGᗩ ᒪᗩᐯᗪE Kᗩᒪᑭ ᗰᗩT😂😂🔥",
    "TEᖇII ᗷEᕼEᑎ KI ᑕᕼᑌT ᖴᗩᗩᗪ KE ᑌSᗰE ᗪYᑎᗩᗰITE ᒪᗩGᗩ KE ᗷᒪᗩST KᗩᖇᗪᑌᑎGᗩ ᗷᕼOSᗪIKE🧨👻☠️",
    "TEᖇII ᗰᗩᗩ Kᗩ ᖇᗩᑭE KᗩᖇKE ᑌSKE 1000 TᑌKᗪE KᗩᖇKE KᑌTTO KO KᕼIᒪᗩ ᗪᑌᑎGᗩ ᖇᗩᑎᗪI KE ᗷᗩᑕᕼᕼE👻💦🍆🔥",
    "TEᖇII ᗰᗩ KI ᑕᕼᑌT ᗰᗩI ᒍᗩᗷ ᗰEᖇᗩ ᒪᗩᐯᗪᗩ ᒍᗩᗩTᗩ ᕼᗩI Tᗩᗷ TEᖇII ᗰᗩᗩ ᗷOᕼOT KᕼᑌSᕼ ᕼOTI ᕼᗩI ᗷSᗪK💦👻🍆🍑",
    "TEᖇII ᗰᗩᗩ KI ᑕᕼᑌT ᖴᗩᗩᗪ ᗪI ᗷSᗪK ᗩᗷ KᗩᒪᗩᑭᗩT ᗷETᗩ ᗷEᕼEᑎ ᑕᕼOᗪᑎE KI TᗩYᗩᖇI Kᗩᖇ ᖇᗩᕼᗩ ᕼᑌ☠️💦🍆🍑🔥",
    "ᗷᕼOSᗪIKE SᑭEEᗪ ᗪEKᕼ ᖇᗩᕼᗩ GᒪᗩᗪIᗩTOᖇ ᗷOT ᕼᗩI Gᗩᗩᑎᗪ ᖴᗩᗩᗪ Kᖇ ᖇᗩKᕼ ᗪEGᗩ TEᖇIII ᗰᗩᗪᗩᖇᑕᕼOᗪ🔥🔥👻😈",
    "TEᖇII ᗰᗩᗩ Kᗩᒪᑭ ᖇᗩᕼI ᕼᗩI ᑌSKO Sᗩᗰᗷᕼᗩᒪ😈💦 ᗩᗷᕼI TEᖇII ᗷEᕼEᑎ KO KᗩᒪᑭᗩᑌᑎGᗩ ᗷSᗪK 👻💦🍆🍑🔥",
    "ᗷᗩᗩᑭ SE ᑭᗩᑎGᗩ ᒪEKᖇ GᗩᒪTI KᗩᖇᗪI ᗷETE ᗩᗷ Gᗩᑎᗪᗩ ᑕᕼᑌᗪEGᗩ Tᑌ😈🔥💦🍆🍑",
    "TEᖇII ᗰᗩᗩ KO Kᒪᑭᗩ Kᒪᑭᗩ KE ᑕᕼOᗪᑌᑎGᗩ ᗷᕼOSᗪIKE 🍆🍑🔥",
    "ᗷᕼOSᗪIKE TEᖇII ᗰᗩᗩ Kᗩ ᗰᗰS ᖇEᑕOᖇᗪ KᗩᖇKE ᙭ᑎ᙭᙭.ᑕOᗰ ᗩᑌᖇ ᑭOᖇᑎᕼᑌᗷ.ᑕOᗰ ᑭᖇ ᗪᗩᒪᑌᑎGᗩ😂😘🔥",
    "TEᖇII ᗰᗩ ᖇOᘔ ᖇEᗪᒪIGᕼT ᑭE 1000 ᗰᗩI Gᗩᗩᑎᗪ ᗩᑌᖇ ᑕᕼᑌT ᗪETI ᕼᗩI😂😂🍑",
    "TEᖇI ᗷEᕼEᑎ KO ᖇOᘔ ᗪEKᕼTᗩ ᕼᑌ ᑭOᖇᑎᕼᑌᗷ.ᑕOᗰ ᑭE ᖇOᘔ SᗩᗩᒪI 10 ᒪOGO Kᗩ ᒪᑌᑎᗪ EK SᗩTᕼ ᒪETI ᕼᗩI😂💦👻",
    "TEᖇII ᗰᗩᗩ Kᗩ ᗷSᗪᗩ ᗩᗷ ᑕᕼᑌᗪ GᗩYᗩ TOᕼ Kᗩᒪᗩᑭ ᖇᗩᕼᗩ ᖇᑎᗪI Kᗩ ᗷᗩᑕᕼᕼᗩ😈😂😘",
    "TEᖇII ᗰᗩᗩ KI ᑕᕼᑌT ᖴᗩᗩᗪ KE ᗷᗩᑕᕼᕼE ᑎIKᗩᒪ ᗪᑌᑎGᗩ SᗩᗩᖇE ᗷSᗪK😂😘👻",
    "TEᖇE Gᗩᗩᑎᗪ ᗰᗩI 10 ᖴEET Kᗩ Gᗩᖇᗩᗰ ᖇOᗪ ᗪᗩᗩᒪᗪᑌᑎGᗩ ᗷSᗪK ᖴIᖇ ᗰᑌᕼ SE ᕼᗩGEGᗩ😂🔥🍆",
    "TEᖇII ᗷEᕼEᑎ KI KᗩᗩᒪI ᑕᕼᑌT ᗰᗩI ᗰEᖇᗩ ᒪᑌᑎᗪ ᗪᗩᗩᒪKE ᖇOᘔ ᗷᗩᑕᕼᕼᗩ ᑭᗩIᗪᗩ KᗩᖇᑌᑎGᗩ😂🍆💦",
    "ᗩᒍEEᗷ ᗷᗩᗩT ᕼᗩI ᗷSᗪK Tᑌ ᗰEᖇᗩ ᗷETᗩ ᗩᑌᖇ Sᗩᗩᒪᗩ ᗪOᑎO ᒪᗩGTᗩ ᕼᗩI ᗩISE KᗩISE Sᗩᗰᗩᒍ ᑎᗩᕼI ᖇᗩᕼᗩ 😂👻😈",
    "TEᖇII ᗰᗩᗩ KO ᑕᕼOᗪKᖇ TᑌᒍᕼE ᑭᗩIᗪᗩ KIYᗩ ᖴIᖇ TEᖇII ᗷEᕼEᑎ KO ᑕᕼOᗪKᖇ ᑌSKᗩ ᗷᗩᑕᕼᕼᗩ ᑭᗩIᗪᗩ KIYᗩ💦🍆👻",
    "ᑭᗩᑭᗩ SE ᒪᗩᗪᑎE KI ᗩᑌKᗩT ᑎᗩᕼI ᗷSᗪK TEᖇI Gᗩᗩᑎᗪ ᗰᖇᗩ 😂😈🔥",
    "TEᖇIII ᗰᗩᗩᗩ KE ᗰᑌᕼ ᗰEIᑎ KᕼᗩᒪI Kᗩ ᗰIᑕ ᒪᗩGᗩ ᗪᑌᑎGᗩ 😱😱😱😱 ᑭᕼIᖇ ᗯOᕼ ᗷᗩᕼᑌT ᒍOᖇ ᒍOᖇ SE EᑕᕼO KE SᗩᗩTᕼ ᑕᕼIᒪᗩYEGI 😹😹😹😹😹",
    "TEᖇIIII ᗰᗩᗩ KE ᗷᕼOSᗪᗩ ᗰEIᑎ ᑭIKᗩ᙭ᕼᑌᑌᑌᑌ Kᗩ ᒪIGᕼTIᑎG ᗷOᒪT Kᗩᖇᗯᗩ ᗪᑌᑎGᗩ 🌩🌩 ᑌSKI ᙭ᕼᑌTTTT 💦💦💦 Kᗩ Sᗩᖇᗩ ᑭᗩᑎI SᑌKᕼ ᒍᗩYEGᗩ 😹😹😹😹",
    "TEᖇIII ᗰᗩᗩᗩ KO ᑭIYᑌSᕼ KE ᖇOYᗩᒪ ᒪᗩᑌᑎᗪ 👑 SE ᖇOYᗩᒪ TᗩᖇIKE 👙 ᗰEIᑎ ᙭ᕼᑌᗪᗯᗩᑌᑎGᗩ 🍌🍑 TEᖇI ᗰᗩᗩ ᗷᕼI ᖇOYᗩᒪ ᖇᗩᑎᗪI ᗷᗩᑎ ᒍᗩYEGI 😹😹😹😹",
    "TEᖇIII ᗩᗰᗰᗩ KI ᙭ᕼᑌT 👅👅👅 ᗰEIᑎ Sᗩᗪᗩ ᒪᗩᑌᑎᗪ ᗷᗩᗪᗩ ᗷᗩᗪᗩ 🍌🍌🍌🍌🍌 GᕼᑌSᗩ ᗪEᑎGE ᑭᕼIᖇ TEᖇIII ᗩᗰᗰᗩ Kᗩ ᗷᕼOSᗪᗩ ᗷᕼI ᗷᗩᗪᗩ ᗷᗩᗪᗩ ᕼOᒍᗩYEGᗩ 😱😱😱😱",
    "TEᖇIIIII ᗷᕼEᑎᗯᗩ Kᗩ ᗷᕼOSᗪᗩ ᗰEIᑎ ᑭᑌᖇᗩ Gᗷ ᖇOᗩᗪ 😱😱 KE TᕼᗩᖇKI ᒪᗩᑌᑎᗪO Kᗩ ᒪᗩᑌᑎᗪ ᗪᗩᒪᗯᗩ ᗪEᑎGE 🍌💦",
    "TEᖇIIIII ᗩᗰᗰᗩ KI ᙭ᕼᑌT ᑭIKᗩᑕᕼᑌ SE ᑕᕼᗩTᗯᗩ ᗪᑌᑎGᗩ 😈❌😈❌😈 👅👅👅👅",
    "TEᖇIIII ᗰᗩᗩᗩ KI ᑕᕼᑌT 🍑 ᗰEIᑎ ᑭIYᑌSᕼ ᑕᕼᗩTᑎI ᒪᗩGᗩKE 😋 ᑕᕼᗩᑎᗪIᑎI ᑕᕼOᗯK 🛣 ᑭE ᑕᕼᗩᑎᗪI KE ᑕᕼᗩᗰᗩᑕᕼ 🥄 SE ᑕᕼᗩT ᒍᗩYEGᗩ 👅👅😹😹😹😹",
    "KᕼᗩᒪI ᑎE TEᖇIIIIII ᗰᗩᗩ KI ᙭ᕼᑌTTTT ITᑎI ᗷᑌᖇI Tᗩᖇᗩᕼ ᗰᗩᖇI 😈 KI TEᖇI ᗰᗩᗩ KO ᕼOGᗩYI ᑕᗩᑎᑕEᖇ KI ᗷIᗰᗩᖇI 😱😱😱😱😱😱",
    "TEᖇIIIII ᗩᗰᗰᗩ KI ᙭ᕼᑌT ᗰEIᑎ ᑭIKᗩᑕᕼᑌ ᑎE ᗪIYᗩ ᗰOOT 🤣🍌💦",
    "TEᖇI ᗷᕼEᑎᗯᗩ Kᗩ ᗷᖇᗩ ᖴᕼᗩᗪ KE ᑌSKI ᗷOOᗷS ᙭ᕼᗩT ᒍᗩᑌᑎGᗩ 💋😋",
    "TEᖇIII ᗰᗩᗩ KO ᑭIYᑌSᕼ ᑭE ᑕᖇᑌSᕼ ᕼᗩI ᑎᗩ 🤔🤥 EK Kᗩᗩᗰ KᗩᖇTE ᕼᗩIᑎ ᑭIYᑌSᕼ Kᗩ ᒪᗩᑌᑎᗪ TEᖇIII ᗰᗩᗩ KI ᙭ᕼᑌT ᗰEIᑎ ᑕᖇᗩSᕼ Kᗩᖇᗯᗩ ᗪETE ᕼᗩIᑎ 🤣😈🍌💦",
    "ᒍᑌᑎGᒪE ᒍᑌᑎGᒪE ᗰᗩIᑎ ᙭ᕼᗩᒪᗩ 😈😈 ᗰᑌᒍᕼE ᗰIᒪI EK ᖇᗩSSI ⛓ ᒪᗩᗯᗪE TEᖇI ᗰᗩᗩ KI ᙭ᕼᑌT ᗰᗩᖇᑌ 🍌🍑 ᗷᗩᑕᑕᕼE ᕼOᑎGE 180 🍌💦",
    "TEᖇIIII ᗰᗩᗩ KE KᗩᒪE ᗷᕼOSᗪE ᗰEIᑎ GᒪᗩᗪIᗩTOᖇS Kᗩ ᗷᗩᗪᗩ Kᗩᒪᗩ ᒪᗩᑌᑎᗪ 😹😹 ITᗪᗩᗰ ᑭEᖇᖴEᑕT ᑕOᗰᗷO ᕼᗩI 🖤👌",
    "TEᖇI ᗰᑌᗰᗰY KI GᗩᑎᗪI GᗩᑎᗪI ᙭ᕼᑌT ᗰEIᑎ GᗩᑎᗪE GᗩᑎᗪE KEEᗪE ᑭᗩᗪE 🤮😷",
    "TEᖇIIIII ᗰᑌᗰᗰY ᗰEᖇᗩ ᒪEGI 😈 TOᕼ KEᒪᗩ ᗰIᒪEGᗩ 🍌💋 ᗯᗩISE ᗷᕼI ᑕOᒪOᑎEY Kᗩ ᒪᗩᗪKᗩ ᒪOG TEᖇI ᗰᗩᗩ Kᗩ Gᗩᑎᗪ ᖴᕼᗩᗪ ᗪEGᗩ 😈❌😈❌😈",
    "TEᖇIIIII ᗰᗩᗩ KE ᑎᑌᗪES Sᑎᗩᑭ᙭ᕼᗩT ᑭE 10 ᖇᑌᑭEE ᗰEIᑎ ᗷE᙭ᕼ ᗪᑌᑎGᗩ 🤤🤑",
    "😈😈 KᕼᗩᒪI ᒍᗩᗷ TEᖇIIII ᗰᗩᗩ ᙭ᕼOᗪEGᗩ 🍌💦 Tᗩᗷ TEᖇI ᗰᗩᗩ KI ᙭ᕼᑌT ᕼE ᖴᕼᗩT KE GᗩYᗩᗷ ᕼOᒍᗩYEGI 😱😱😹😹",
    "KᕼᗩᒪI ᑎE ᙭ᕼOᗪᗩ TEᖇI ᗰᗩᗩ KO 😈🍌💦 TEᖇI ᗰᗩᗩ ᑎE ᗷOᒪᗩ ᙭ᕼOᖇᗪ ᗪEᑎᗩ ᗩᑭᑎI ᒍᗩᗩᑎ KO 🥺🥺",
    "ᒍᗩᗷ TEᖇIIII ᗰᗩᗩ KI Gᗩᑎᗪ 🍑 ᗰEIᑎ Gᗩᖇᗩᗰ Gᗩᖇᗩᗰ ᒪOᕼE Kᗩ ᗪᗩᑎᗪᗩ 😏 ᗪᗩᒪEGᗩ Tᗩᗷ ᑌSKI Gᗩᑎᗪ ᒍᗩᒪEGI 🔥❤️‍🔥 ᗩᑌᖇ ᑌSKO ᑭᗩTᗩ ᑕᕼᗩᒪEGᗩ GᒪᗩᗪIᗩTOᖇS KI ᑭOᗯEᖇ",
    "TEᖇIIII ᗷᕼEᑎ KO IᗰᑭEᖇIᑌᗰ ᗰᗩᖇKET ᑭE 10 ᑕᑕ KI ᒍᗩGᗩᕼ ᗷEᑕᕼ ᗪᑌᑎGᗩ 😹😹😹😹",
    "TEᖇIIII ᗰᗩᗩᗩ KI ᙭ᕼᑌT KO IᗰᑭEᖇIᑌᗰ KE ᕼᗩᑕKEᖇS SE ᕼᗩᑕK KᗩᖇᗯᗩKE ᑎOᑎ STOᑭ SQᑌIᖇT KᗩᖇᗯᗩᑌᑎGᗩ 💦💦😹😹",
    "T3ᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰEIᑎ GᒪᗩᗪIᗩTOᖇS-ᑭᖇOᒍEᑕTS KE ᑭᖇOᒍEᑕTS ᗷᕼᗩᖇ ᗪᑌᑎGᗩ ᑎᗩYE ᑎᗩYE\ᑎ🍌💦🍌💦🍌💦🍌💦🍌💦🍌💦",
    "TEᖇIIII ᗰᗩᗩ KI Gᗩᑎᗪ ᗰEIᑎ GᒪᗩᗪIᗩTOᖇS Kᗩ SᑭEᗩᖇ ᗪᗩᒪKE ᑕᕼEᗪ Kᗩᖇ ᗪᑌᑎGᗩ 😱😹😱😹😱😹😱😹😱",
    "T3ᖇI ᗰᗩᗩ Kᗩ ᗷᕼOSᗪᗩ #ᘔᗩᑎᗪᗩᖇOᑭ ᖴᗩᗩᗪ ᗪEGᗩ ᖴIᖇ Sᗩᗷ ᒪOOTᑎE ᗩᗩ ᒍᗩYEᑎGE\ᑎ🍌🤤🍌🤤🍌🤤🍌🤤🍌",
    "TEᖇIIIII ᗰᗩᗩᗩ KI ᙭ᕼᑌT SE GᒪᗩᗪIᗩTOᖇ Sᑭᗩᗰ ᗷOT KI Tᗩᖇᗩᕼ ᑎOᑎ STOᑭ ᑕᑌᗰ Sᑭᗩᗰ KᗩᖇᗯᗩᑌᑎGᗩ 🍌💦🍌💦🍌💦🍌💦🍌💦🍌",
    "T3ᖇI ᗰᗩᗩ IᗰᑭEᖇIᑌᗰ ᑎETᗯOᖇK ᗰEIᑎ ᑕOᑌᖇSE KᕼᗩᖇIᗪᑎE KE ᒪIYE ᗰᑌᒍᖇᗩ Kᖇ ᖇᕼI\ᑎ🤤💦🤤💦🤤💦🤤💦🤤💦",
    "ᕼᗩᖇYᗩᑎᗩ ᗩᒪᒪᗩ TEᖇI ᗷᕼEᑎ KO ᙭ᕼOᗪᑎE ᗯᗩᒪᗩ TEᖇI ᗷᕼEᑎ Kᗩ ᑭᗩTI  TEᖇᗩ ᒍIᒍᗩ ᙭ᕼETᗩᑎ ❌❌❌❌❌❌❌❌❌❌",
    "TEᖇIIII ᗰᗩᗩ KE ᑎᑌᗪES KO ᙭ᗩᖇᗪIᑎG KᗩᖇKE IᗰᑭEᖇIᑌᗰ ᑎETᗯOᖇK SE KᕼᗩᖇIᗪ ᒪᑌᑎGᗩ 😹😹😹😹😹",
    "TEᖇIIIII ᗰᗩᗩ ᗰEᖇEKO GᒪᗩᗪIᗩTOᖇS ᗩᖇᗰY KE ᐯᑕ ᑭE Gᗩᑎᗪ ᗪEKᕼᗩ ᖇᗩᕼI\ᑎ🍑💦🍑💦🍑💦🍑💦🍑💦",
    "ᗰᗩᗩᗩᗩᗩᗪᗩᗩᖇᑕᑕᕼOᗪ TEEEᖇᖇᖇᖇII ᗰᗩᗩᗩᗩᗩ KOO\ᑎ ᑎᗩᑎGᗩ KᗩᖇKE ᑭIKᗩᑕᕼᑌ ᗩᑌᖇ ᗪEEᑭᗩK😈 SᗩᗪᗩK KE ᗷEEᑕᕼ ᗰEIᑎ ᒪEEETᗩᗩᗩ KE ᑭEᒪEGᗩ\ᑎ🤘🤫🤣🤣🤤",
    "SᗩᗩᗩᒪEEEE  TEEᖇIIII ᗰᗩᗩᗩᗩᗩ KIIIIII ᑕᕼᑌTTT ᗩESEEEEE ᗰᗩᗩᖇᖇᑌᑎGᗩᗩᗩ ᑎᗩᗩᗩᗩ\ᑎKIIII SᑌᖇᗩᑎG ᗷᑌᑎᑎᑎ ᒍᗩYEGI ᗷEᕼᗩᑎᑕᕼOᗪ\ᑎᑌSᗰEEE ᒪᗩᗩᗩᑎᗪᗪ ᗰIᑎE ᗷIᑕᕼᗩᗩᗩᗩᗩᗩ KEEEEEEEE ᑌᗪᗩᗩᗩᗩᗩ ᗪᑌᑎGᗩᗩᗩᗩᗩ\ᑎTEEEEᖇIIIIIIII ᗰᗩᗩᗩᗩᗩᗩ Kᗩᗩᗩᗩᗩ ᗷᕼOSᗪᗩᗩᗩᗩ ᑌᗪᗪᗪᗪᗪᗪ ᒍᗩᗩᗩYEGᗩᗩᗩ ᗰᗩᗩᗪᗩᖇᑕᕼO\ᑎ🤘😂😜😋🤭🤣🤣🤫🤫🤫🤫🤧🤧🤧🤧🤧😇😇😇😇🥱🥱🥱",
    "TEEEᖇIIIIII ᗰᗩᗩᗩᗩᗩ KIIIII ᑕᕼᑌTTTTT ᗰEIᑎ ᗩEᖇOᑭᒪᗩᑎE ✈️🛫✈️🛫 ᗪᗩᗩᗩᗩᗩᒪ KEEEEE ᑌᗪᗩᗩᗩᗩᗩ ᗪᑌᑎGᗩ\ᑎ ᗰᗩᗩᗩᗩᗩᗪᗩᗩᗩᖇᑕᕼOᗪ\ᑎ🤤🤘Tᑌᑌᑌᑌᑌᑌᑌ ᗩᗩᑌᖇᖇ TEᖇIIIIII ᗷEᕼᗩᑎᑎᑎᑎᑎ IᑎᗪIᗩ ᗰEIᑎ ᑕᕼᑌᗪᗯᗩᗩᑎᗩᗩ\ᑎTEᖇIIIIIIII ᗰᗩᗩᗩᗩᗩᗩᗩᗩ ᗷᗩᗩᗩᗩᕼᗩᗩᗩᖇ ᑕᕼᑌᗪᗯᗩᗩᗩᗩᗩYEGIIII\ᑎKᗩᗷᕼIIIII ᗩᑌSTᖇᗩᒪIᗩ 🌏 KᗩᗷᕼI ᑌSᗩ KᗩᗷᕼI EᑎGᒪᗩᑎᗪ\ᑎ🤤🤤🤤🤤🤤🤤👅👅👅👅👄👄👄👄👄👄👄💋💋💋💋💋💋",
    "TEEEᖇIIIIII ᗰᗩᗩᗩᗩᗩᗩᗩ ᗷEEEᕼᗩᗩᗩᗩᑎ KEEEEE ᗷᕼOSᗩᗪE ᗰEIᑎ ᑭᗩTᗩᑎG\ᑎ ᗪᗩᗩᗩᗩᗩᗩᗩᗩᒪ KEEEEE ᑌᗪᗩᗩᗩᗩᗩ ᗪᑌᑎGᗩ\ᑎ ᗰᗩᗩᗩᗩᗩᗪᗩᗩᗩᖇᑕᕼOᗪ\ᑎ🤤🤤😂😂😂🤭😙😙😜😜😎😎",
    "😈😈👅👅👅👅👅💩💩💩💩👻👻👻👻👻👻👻☠️🤑🤑🤑🤑🎃🎃🎃🎃🎃🥵🥵🥵🥵🥵\ᑎTEEEEᖇᖇᖇIIIIIIII ᗰᗩᗩᗩᗩᗩᗩ ᗩEESEEE ᑕᕼOᗪI KI TEᖇIIIIIIII ᗰᗩᗩᗩᗩ ᗩESE ᕼI ᖇᗩᑎG ᗷIᖇᗩᗩᗩᑎGI ᕼOOOOO GYIIIIIII ᗷSᗪK ᗩᗷ TEᖇIIIIII ᗩᑌᖇ ᗷEᕼᗩᑎ KI ᗷᗩᗩᗩᗩᖇI ᗩᗷᗷᗷᗷᗷᗷ ᗪEEᑭᗩK ᑭEᒪEGᗩ ᗰᗩᗩᗪᗩᖇᑕᕼOᗪ Sᗩᗰᗷᕼᗩᗩᒪ KE Sᗩᗰᗷᕼᗩᗩᒪ SᗩKTᗩᗩᗩᗩᗩ ᕼᗩIIIIII TOOOOOOO🤤🤤🤤🤤👅👅👅👅👅",
    "ᗷᗩᗩᗩᗩᗩᑭ SEEEE ᑭᗩᗩᑎGᗩᗩᗩ ᒪEEEEE ᒪIYᗩᗩᗩᗩ ᗰᗩᗩᗩᗩᗩᗪᗩᗩᗩᖇᑕᕼOᗪ\ᑎ ᑕᕼᗩKKEE ᗪEKᕼ ᗩᗩᗩᗷᕼI TEᖇIIIIIIII ᗰᗩᗩᗩᗩᗩᗩᗩ KEISE ᑕᕼᑌᗪEEGIIIII ᗷSᗪK ᖇᗩᑎᗪE\ᑎ 🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤘🤘🤘🤘🤘🤘🤘",
    "TEᖇIIIIIIII ᗰᗩᗩᗩᗩᗩᗩ KE ᗷᕼOSᗩᗪE ᗰEIᑎ ᗪᗩᑎᗪᗩᗩᗩ ᗪᗩᗩᗩᗩᒪ KEEEE Kᕼᗩᗩᗩᗪᗩᗩᗩ Kᖇ ᗪᑌᑎGᗩ\ᑎ ᗰᗩᗩᗩᗩᗩᗪᗩᗩᗩᖇᑕᕼOᗪ\ᑎ😋🤤🤤🤤🤤🤤✈️✈️✈️🤤🤤🤤",
    "TEEᖇᖇᖇIIIII ᗰᗩᗩᗩᗩ KEEE ᑭᕼᗩᗩᗩTEEE ᗷᕼᕼOOSᗩᗩᗪE\ᑎ Kᗩᗩᗩᗩ SᕼIIIIIKᗩᗩᗩᗩᗩᖇIIII ᕼᗩᗩᗩIIIIII ᗪEEᑭᗩK SᗩᗩᒪE ᑕᕼᗩKKEE\ᑎ🤭🤤🤤🤨",
    "ᖇᗩᗩᗩᗩᑎᗪᗪᗪIIIIIIII KEEEEE ᑭIᒪᒪᒪᒪᒪᒪEE ᗰᗩᗩᗩᗩᗩᗪᗩᗩᗩᖇᑕᕼOᗪ😋😁",
    "ᗰᑌᗰᗰYYYY KOOOOO ᗷOᒪᒪᒪᒪ TEᒪᒪ ᒪGᗩᗩᗩᗩ KEEEEE ᖇᗩKᕼEEEE\ᑎTᕼᑌᑌᑌKKKK ᒪGᗩᗩᗩᗩᗩᗩ KEEEEEE ᗰᗩᗩᗩᗩᖇᑎEEEE ᑎᕼI ᗪEETI ᐯOOOOOO\ᑎ🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤",
    "TᗴᖇI ᗰᗩᗩ ᗷᗴᕼᗩᑎ ᗪᗴᗴᑭᗩK😆ᑭᗴᒪᗴ\ᑎᗰᗩᗩ Kᗴ ᒪOᗯᗪᗴ\ᑎ😘😜🤓🤓🤓",
    "Tᑌᑌ ᒪEEGᗩᗩ ᕼᑌᗰSE ᑭᗩᑎGᗩ😋\ᑎSᗩᗩᒪE ᗪEEᑭᗩK😈 ᗩᑌᖇ ᑭIKᗩᑕᕼᑌ 🤓 ᑭEᒪEᑎGE TᑌᒍᕼE KᖇKE ᑎᗩᑎGᗩ\ᑎ🤩🤩😂😂😂🤣",
    "ᗩᗷᗷᗷᗷᗷᗷEEEE😆😆😆ᖇᖇᖇᖇᖇᖇᖇᑎᑎᗩᗩᗩᗪᗪᗪᗪᗪᗪᗪᗪII\ᑎ🤣🤣🤣ᗰᗰᗩᗩᗩᗩ😥😥KKEEEEE😃\ᑎᗷᗷᗷᗷᗷᗷᗷᗩᑕᑕᑕᑕᕼᕼᕼᕼEEEEEEEEEEE👅👅👅👅👅",
    "ᑭᗩKᗩᗪ ᑭᗩKᗩᗪ Տᑭᗴᗴᗪ ᑭᗩKᗩᗪ😒😒\ᑎᗰᗩᗩ Kᗴ ᒪOᗯᗪᗴ ᖇᗩᑎᗪI Kᗴ ᑭIᒪᒪᗴ\ᑎ😤😤",
    "ᗷᗩᗩᑭ SE ᒪᗩᗪEGᗩ TO\ᑎᗰᑌᗰᗰY ᕼI ᑕᕼᑌᗪEGI ᑎᗩᗩ ᖇᗩᑎᗪI ᗰE ᑭIᒪᒪE🙄🤤🥴🥴\ᑎTᑌ ᗷOᒪEGᗩ ᗷᗩᗩᑭ KE SᗩᗩᗰᑎE ᗰᗩᗩᗪᗩᖇᑕᕼOᗪ\ᑎ😒😏🤬🤬🥵🥵",
    "𝖢𝖧𝖠ᕼE ᕼO ᑭᑌᑎITᕼ😒ᑕᕼᗩᕼE ᕼO Tᕼᗩᑭᗩ🙄\ᑎSᗩᗩᒪE ᗪEEᑭᗩK ᗩᑌᖇ ᑭIKᗩᑕᕼᑌ KO ᑕᕼOᖇ KE\ᑎ KᗩᗷᕼI ᕼᑌᗰE ᗷᕼI ᗷOᒪᗪO ᑭᗩᑭᗩ\ᑎ😤😤😤🥴🥴🥴🥴",
    "ᑭEᕼᒪE ᗰᗩIᑎ TEᖇEKO ᑕᕼᗩKᑎᗩ ᗪEGᗩ, ᖴIᖇ ᗪᗩᖇᑌ ᑭIᒪᗩYEGᗩ, ᖴIᖇ ᒍᗩᗷ ᗩᗩᑭ ᗪIᗰᗩG sE ᑎᗩᕼI ᒪ*ᑎᗪ sE sOᑕᕼOGE, Tᗩᗷ ᗷOᒪEGᗩ..",
    "TEᖇI ᗩᗰᗰY KE sᗩTᕼ ᗰᗩI ᖇOᒪE ᑭᒪᗩY KᗩᖇᑌᑎGᗩ🤣🤣🤣🤣🤣🤣ᑌsKO ᗰᗩᒪIK KI ᗯIᖴE ᗷᗩᑎᗩᑌᑎGᗩ ᗩᑌᖇ Kᕼᑌᗪ ᗪᖇIᐯEᖇ ᗷᗩᑎKE ᑭEᒪᑌᑎGᗩ ᑌsKO!",
    "TEᖇI ᗰᗩᗩ KI Gᗩᗩᗩᗩᑎᗪ ᗰE ᗪᗩᑎᗪᗩᗩ ᗪᗩᗩᒪ KE ᗪᗩᑎᗪᗪᗩ TOᗪᗪ ᗪᑌᑎGᗩᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ ᗷᗩᗩᑭ ᕼᑌ TEᖇᗩ ᗷEᕼEᑎ KE ᒪᑌᑎᗪᗪᗪ",
    "ᑭᕼOOᒪ ᗰᑌᖇᒍᕼᗩTE ᗩᑕᕼᕼE ᑎᗩᕼI ᒪᗩGTE ᗩᗩᑭ ᒪᗩᑎᗪ KᕼᑌᒍᗩTE ᗩᑕᑕᕼE ᑎᗩᕼI ᒪᗩGTE YEᕼI ᑌᗰᗩᖇ ᕼᗩI ᑕᕼOᗪᑎE KI YᗩᗩᖇO ᗩᗩᑭ ᗷᗩTᕼᖇOOᗰ ᗰEIᑎ ᕼIᒪᗩᗩTE ᗩᑕᑕᕼE ᑎᗩᕼI ᒪᗩGTE.",
    "TEᖇI ᗷEᕼᑎ KO ᗷOᒪᑌᑎGᗩ KI ᗰEᖇE ᒪIYE ᑭᗩᗩᑎI ᒪᗩO ᗩᑌᖇ ᒍᗷ ᗯO ᑭᗩᗩᑎI ᒪEᑎE KE ᒪIYE ᒍᕼᑌKEGI TᗷI ᑭEEᑕᕼE sE ᑌTᕼᗩ KE ᑭEᒪ ᗪᑌᑎGᗩ",
    "ᑕᕼIᑎᗩᗩᒪ KE GᗩᗪᗪE KE ᑎIᑭᑭᒪE KE ᗷᗩᗩᒪ KE ᒍOOᑎ- ᑭᖇOsTITᑌTE’s ᗷᖇEᗩsT’s ᑎIᑭᑭᒪE’s ᕼᗩIᖇ’s ᒪIᑕE",
    "TEᖇI ᗰᗩᗩ KI Gᗩᗩᑎᗪ ᗰEIᑎ ᗩᗷᕼI ᗷᕼᗩᖇ ᗷᕼᗩᖇ KE GᗩᗩᒪI ᗪETᗩ ᕼᑌᑎ ᗰᗩᗪᗩᖇᑕᕼOᗪ ᗷᕼOsᗪIKE ᖇᑌK TEᖇI ᗰᗩᗩ Kᗩ ᗷᕼOsᗪᗩ ᖇᗩᑎᗪI Kᗩ ᑭIᒪᒪᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ ᑕᕼᑌs ᒪE ᗰEᖇᗩ ᒪOᗪᗩ ᗷᕼOsᗪIKE",
    "Sᗩᗩᗯᗩᑎ Kᗩ ᗰᗩᕼIᑎᗩ ᑭᗩᗯᗩᑎ KᗩᖇE sᕼOᖇ ᒍᗩKE Gᗩᑎᗪ ᗰᗩᖇᗩ ᗷsKᗪ KᗩᕼI ᗩᑌᖇ.",
    "ᕼEY ᗰEᖇE ᗷETE KᗩIsE ᕼO ᗷETᗩ Tᑌᗰ\ᑎᑌss ᖇᗩᗩT ᒍᗩᗷ ᗰᗩIᑎE TEᖇI ᗰᗩᗩ ᑕᕼOᗪᗩ Tᕼᗩ ᒍIsKE 9 ᗰᗩᕼIᑎE ᗷᗩᗩᗪ Tᑌᗰ ᑭᗩIᗪᗩ ᕼᑌE ᗷᕼOT ᗰᗩᘔᗩ ᗩᗩYᗩ Tᕼᗩ ᗰᑌᒍᕼE ᗩᑌᖇ TEᖇI ᗰᗩᗩ KO ᗷᕼI!!",
    "TEᖇI ᗰᗩᗩ KI Gᗩᗩᑎᗪ ᗰEIᑎ ᗩᗷᕼI ᗷᕼᗩᖇ ᗷᕼᗩᖇ KE GᗩᗩᒪI ᗪETᗩ ᕼᑌᑎ ᗰᗩᗪᗩᖇᑕᕼOᗪ ᗷᕼOsᗪIKE ᖇᑌK TEᖇI ᗰᗩᗩ Kᗩ ᗷᕼOsᗪᗩ ᖇᗩᑎᗪI Kᗩ ᑭIᒪᒪᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ ᑕᕼᑌs ᒪE ᗰEᖇᗩ ᒪOᗪᗩ ᗷᕼOsᗪIKE",
    "TEᖇIIIIIIII ᗰᗩᗩᗩᗩᗩᗩᗩᗩᗩᗩ KI ᑕᕼᑌTTTTT ᗰEEEEEEEEE GᕼOᗪEEEE Kᗩ ᒪᑌᑎᗪᗪᗪᗪᗪᗪᗪ ᗰᗩᗪᗩᖇᑕᕼOᗪᗪᗪᗪᗪᗪᗪ GᗩSTI KE ᗷᗩ᙭ᕼEEEEE",
    "TEᖇI ᗰᗩᗩ Kᗩ ᗰᗩᖇS ᑭE KOTᕼᗩ KᕼᑌᒪᗯᗩᗩᑌᑎGᗩ 🔥😂",
    "ᖇᗩᑎᗪI KE ᑭIᒪᒪE",
    "TEᖇIIIII ᗰᗩᗩᗩ KO ᗷᕼEᒍᒍᒍ",
    "TEᖇᗩᗩ ᗷᗩᗩᗩᗩᑭ ᕼᑌ",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰE ᕼᗩᗩT ᗪᗩᗩᒪᒪKE ᗷᕼᗩᗩG ᒍᗩᗩᑎᑌGᗩ",
    "TEᖇI ᗰᗩᗩ KO SᗩᖇᗩK ᑭE ᒪETᗩᗩ ᗪᑌᑎGᗩ",
    "TEᖇI ᗰᗩᗩ KO Gᗷ ᖇOᗩᗪ ᑭE ᒪEᒍᗩKE ᗷEᑕᕼ ᗪᑌᑎGᗩ",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰÉ KᗩᗩᒪI ᗰITᑕᕼ",
    "TEᖇI ᗰᗩᗩ SᗩSTI ᖇᗩᑎᗪI ᕼᗩI",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰE KᗩᗷᑌTᗩᖇ ᗪᗩᗩᒪ KE SOᑌᑭ ᗷᗩᑎᗩᑌᑎGᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ",
    "TEᖇI ᗰᗩᗩᗩ ᖇᗩᑎᗪI ᕼᗩI",
    "TEᖇI ᗰᗩᗩᗩ KI ᑕᕼᑌT ᗰE ᗪETOᒪ ᗪᗩᗩᒪ ᗪᑌᑎGᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ",
    "TEᖇI ᗰᗩᗩ Kᗩᗩᗩ ᗷᕼOSᗪᗩᗩ",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰE ᒪᗩᑭTOᑭ",
    "TEᖇI ᗰᗩᗩ ᖇᗩᑎᗪI ᕼᗩI",
    "TEᖇI ᗰᗩᗩ KO ᗷISTᗩᖇ ᑭE ᒪETᗩᗩKE ᑕᕼOᗪᑌᑎGᗩ",
    "TEᖇI ᗰᗩᗩ KO ᗩᗰEᖇIᑕᗩ GᕼᑌᗰᗩᗩᑌᑎGᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰE ᑎᗩᗩᖇIYᗩᒪ ᑭᕼOᖇ ᗪᑌᑎGᗩ",
    "TEᖇI ᗰᗩᗩ KE Gᗩᑎᗪ ᗰE ᗪETOᒪ ᗪᗩᗩᒪ ᗪᑌᑎGᗩ",
    "TEᖇI ᗰᗩᗩᗩ KO ᕼOᖇᒪIᑕKS ᑭIᒪᗩᑌᑎGᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ",
    "TEᖇI ᗰᗩᗩ KO SᗩᖇᗩK ᑭE ᒪETᗩᗩᗩ ᗪᑌᑎGᗩᗩᗩ",
    "TEᖇI ᗰᗩᗩ Kᗩᗩ ᗷᕼOSᗪᗩ",
    "ᗰEᖇᗩᗩᗩ ᒪᑌᑎᗪ ᑭᗩKᗩᗪ ᒪE ᗰᗩᗪᗩᖇᑕᕼOᗪ",
    "ᑕᕼᑌᑭ TEᖇI ᗰᗩᗩ ᗩKᗩᗩ ᗷᕼOSᗪᗩᗩ",
    "TEᖇIII ᗰᗩᗩ ᑕᕼᑌᖴ GEYII KYᗩᗩᗩ ᒪᗩᗯᗪEEE",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰEIᑎ ᗪIYᗩ GᒪᗩᗪIᗩTOᖇs ᑎE ᗰOOT!!",
    "GOTE KITᑎE ᗷᕼI ᗷᗩᗪEY ᕼO, ᒪᑌᑎᗪ KE ᑎIᑕᕼE ᕼI ᖇEᕼTEIᑎ ᕼᗩIᑎ… ",
    "ᗰᗩᗪᗩᖇᑕᕼOᗪ TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰE GᕼᑌTKᗩ KᕼᗩᗩKE TᕼOOK ᗪᑌᑎGᗩ 🤣🤣",
    "TEᖇE ᗷEᕼEᑎ K ᑕᕼᑌT ᗰE ᑕᕼᗩKᑌ ᗪᗩᗩᒪ Kᗩᖇ ᑕᕼᑌT Kᗩ KᕼOOᑎ Kᗩᖇ ᗪᑌGᗩ",
    "TEᖇI ᐯᗩᕼEEᑎ ᑎᕼI ᕼᗩI KYᗩ? 9 ᗰᗩᕼIᑎE ᖇᑌK SᗩGI ᐯᗩᕼEEᑎ ᗪETᗩ ᕼᑌ 🤣🤣🤩",
    "TEᖇI ᗰᗩᗩ K ᗷᕼOSᗪE ᗰE ᗩEᖇOᑭᒪᗩᑎEᑭᗩᖇK KᗩᖇKE ᑌᗪᗩᗩᑎ ᗷᕼᗩᖇ ᗪᑌGᗩ ✈️🛫",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰE SᑌTᒪI ᗷOᗰᗷ ᖴOᗪ ᗪᑌᑎGᗩ TEᖇI ᗰᗩᗩ KI ᒍᕼᗩᗩTE ᒍᗩᒪ KE KᕼᗩᗩK ᕼO ᒍᗩYEGI💣",
    "TEᖇI ᗰᗩᗩKI ᑕᕼᑌT ᗰE SᑕOOTEᖇ ᗪᗩᗩᒪ ᗪᑌGᗩ👅",
    "TEᖇE ᗷEᕼEᑎ K ᑕᕼᑌT ᗰE ᑕᕼᗩKᑌ ᗪᗩᗩᒪ Kᗩᖇ ᑕᕼᑌT Kᗩ KᕼOOᑎ Kᗩᖇ ᗪᑌGᗩ",
    "TEᖇE ᗷEᕼEᑎ K ᑕᕼᑌT ᗰE ᑕᕼᗩKᑌ ᗪᗩᗩᒪ Kᗩᖇ ᑕᕼᑌT Kᗩ KᕼOOᑎ Kᗩᖇ ᗪᑌGᗩ",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT KᗩKTE 🤱 GᗩᒪI KE KᑌTTO 🦮 ᗰE ᗷᗩᗩT ᗪᑌᑎGᗩ ᑭᕼIᖇ 🍞 ᗷᖇEᗩᗪ KI Tᗩᖇᕼ KᕼᗩYEᑎGE ᗯO TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT",
    "ᗪᑌᗪᕼ ᕼIᒪᗩᗩᑌᑎGᗩ TEᖇI ᐯᗩᕼEEᑎ KE ᑌᑭᖇ ᑎIᑕᕼE 🆙🆒😙",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰE ✋ ᕼᗩTTᕼ ᗪᗩᒪKE 👶 ᗷᗩᑕᑕᕼE ᑎIKᗩᒪ ᗪᑌᑎGᗩ 😍",
    "TEᖇI ᗷEᕼᑎ KI ᑕᕼᑌT ᗰE KEᒪE KE ᑕᕼIᒪKE 🍌🍌😍",
    "TEᖇI ᗷᕼEᑎ KI ᑕᕼᑌT ᗰE ᑌSEᖇᗷOT ᒪᗩGᗩᗩᑌᑎGᗩ SᗩSTE Sᑭᗩᗰ KE ᑕᕼOᗪE",
    "TEᖇI ᐯᗩᕼEEᑎ ᗪᕼᗩᑎᗪᕼE ᐯᗩᗩᒪI 😋😛",
    "TEᖇI ᗰᗩᗩ KE ᗷᕼOSᗪE ᗰE ᗩᑕ ᒪᗩGᗩ ᗪᑌᑎGᗩ SᗩᗩᖇI GᗩᖇᗰI ᑎIKᗩᒪ ᒍᗩᗩYEGI",
    "TEᖇI ᐯᗩᕼEEᑎ KO ᕼOᖇᒪIᑕKS ᑭEEᒪᗩᑌᑎGᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ😚",
    "TEᖇI ᗰᗩᗩ KI Gᗩᗩᑎᗪ ᗰE SᗩᖇIYᗩ ᗪᗩᗩᒪ ᗪᑌᑎGᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ ᑌSI SᗩᖇIYE ᑭᖇ TᗩᑎG KE ᗷᗩᑕᕼE ᑭᗩIᗪᗩ ᕼOᑎGE 😱😱",
    "TEᖇI ᗰᗩᗩ KO KOᒪKᗩTᗩ ᐯᗩᗩᒪE ᒍITᑌ ᗷᕼᗩIYᗩ Kᗩ ᒪᑌᑎᗪ ᗰᑌᗷᗩᖇᗩK 🤩🤩",
    "TEᖇI ᗰᑌᗰᗰY KI ᖴᗩᑎTᗩSY ᕼᑌ ᒪᗩᗯᗪE, Tᑌ ᗩᑭᑎI ᗷᕼEᑎ KO Sᗰᗷᕼᗩᗩᒪ 😈😈",
    "TEᖇᗩ ᑭEᕼᒪᗩ ᗷᗩᗩᑭ ᕼᑌ ᗰᗩᗪᗩᖇᑕᕼOᗪ ",
    "TEᖇI ᐯᗩᕼEEᑎ KE ᗷᕼOSᗪE ᗰE ᙭ᐯIᗪEOS.ᑕOᗰ ᑕᕼᗩᒪᗩ KE ᗰᑌTᕼ ᗰᗩᗩᖇᑌᑎGᗩ 🤡😹",
    "TEᖇI ᗰᗩᗩ Kᗩ GᖇOᑌᑭ ᐯᗩᗩᒪOᑎ SᗩᗩTᕼ ᗰIᒪKE GᗩᑎG ᗷᗩᑎG KᖇᑌᑎGᗩ🙌🏻☠️ ",
    "TEᖇI ITEᗰ KI Gᗩᗩᑎᗪ ᗰE ᒪᑌᑎᗪ ᗪᗩᗩᒪKE,TEᖇE ᒍᗩISᗩ EK Oᖇ ᑎIKᗩᗩᒪ ᗪᑌᑎGᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ🤘🏻🙌🏻☠️ ",
    "ᗩᑌKᗩᗩT ᗰE ᖇEᕼ ᐯᖇᑎᗩ Gᗩᗩᑎᗪ ᗰE ᗪᗩᑎᗪᗩ ᗪᗩᗩᒪ KE ᗰᑌᕼ SE ᑎIKᗩᗩᒪ ᗪᑌᑎGᗩ SᕼᗩᖇIᖇ ᗷᕼI ᗪᗩᑎᗪE ᒍESᗩ ᗪIKᕼEGᗩ 🙄🤭🤭",
    "TEᖇI ᗰᑌᗰᗰY KE SᗩᗩTᕼ ᒪᑌᗪO KᕼEᒪTE KᕼEᒪTE ᑌSKE ᗰᑌᕼ ᗰE ᗩᑭᑎᗩ ᒪOᗪᗩ ᗪE ᗪᑌᑎGᗩ☝🏻☝🏻😬",
    "TEᖇI ᐯᗩᕼEEᑎ KO ᗩᑭᑎE ᒪᑌᑎᗪ ᑭᖇ ITᑎᗩ ᒍᕼᑌᒪᗩᗩᑌᑎGᗩ KI ᒍᕼᑌᒪTE ᒍᕼᑌᒪTE ᕼI ᗷᗩᑕᕼᗩ ᑭᗩIᗪᗩ Kᖇ ᗪEGI👀👯 ",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰEI ᗷᗩTTEᖇY ᒪᗩGᗩ KE ᑭOᗯEᖇᗷᗩᑎK ᗷᗩᑎᗩ ᗪᑌᑎGᗩ 🔋 🔥🤩",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰEI ᑕ++ STᖇIᑎG EᑎᑕᖇYᑭTIOᑎ ᒪᗩGᗩ ᗪᑌᑎGᗩ ᗷᗩᕼTI ᕼᑌYI ᑕᕼᑌT ᖇᑌK ᒍᗩYEGIIII😈🔥😍",
    "TEᖇI ᗰᗩᗩ KE Gᗩᗩᑎᗪ ᗰEI ᒍᕼᗩᗩᗪᑌ ᗪᗩᒪ KE ᗰOᖇ 🦚 ᗷᗩᑎᗩ ᗪᑌᑎGᗩᗩ 🤩🥵😱",
    "TEᖇI ᑕᕼᑌT KI ᑕᕼᑌT ᗰEI SᕼOᑌᒪᗪEᖇIᑎG Kᗩᖇ ᗪᑌᑎGᗩᗩ ᕼIᒪᗩTE ᕼᑌYE ᗷᕼI ᗪᗩᖇᗪ ᕼOGᗩᗩᗩ😱🤮👺",
    "TEᖇI ᗰᗩᗩ KO ᖇEᗪI ᑭE ᗷᗩITᕼᗩᒪ KE ᑌSSE ᑌSKI ᑕᕼᑌT ᗷIᒪᗯᗩᑌᑎGᗩᗩ 💰 😵🤩",
    "ᗷᕼOSᗪIKE TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰEI 4 ᕼOᒪE ᕼᗩI ᑌᑎᗰE ᗰSEᗩᒪ ᒪᗩGᗩ ᗷᗩᕼᑌT ᗷᗩᕼETI ᕼᗩI ᗷᕼOᖴᗪIKE👊🤮🤢🤢",
    "TEᖇI ᗷᗩᕼEᑎ KI ᑕᕼᑌT ᗰEI ᗷᗩᖇGᗩᗪ Kᗩ ᑭEᗪ ᑌGᗩ ᗪᑌᑎGᗩᗩ ᑕOᖇOᑎᗩ ᗰEI Sᗩᗷ O᙭YGEᑎ ᒪEKᗩᖇ ᒍᗩYEᑎGE🤢🤩🥳",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰEI SᑌᗪO ᒪᗩGᗩ KE ᗷIGSᑭᗩᗰ ᒪᗩGᗩ KE 9999 ᖴᑌᑕK ᒪᗩGᗩᗩ ᗪᑌ 🤩🥳🔥",
    "TEᖇI ᐯᗩᕼEᑎ KE ᗷᕼOSᗪIKE ᗰEI ᗷESᗩᑎ KE ᒪᗩᗪᗪᑌ ᗷᕼᗩᖇ ᗪᑌᑎGᗩ🤩🥳🔥😈",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT KᕼOᗪ KE ᑌSᗰE ᑕYᒪIᑎᗪEᖇ ⛽️ ᖴIT KᗩᖇKE ᑌSᗰEE ᗪᗩᒪ ᗰᗩKᕼᗩᑎI ᗷᗩᑎᗩᑌᑎGᗩᗩᗩ🤩👊🔥",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰEI SᕼEESᕼᗩ ᗪᗩᒪ ᗪᑌᑎGᗩᗩᗩ ᗩᑌᖇ ᑕᕼᗩᑌᖇᗩᕼE ᑭE TᗩᗩᑎG ᗪᑌᑎGᗩ ᗷᕼOSᗪIKE😈😱🤩",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰEI ᑕᖇEᗪIT ᑕᗩᖇᗪ ᗪᗩᒪ KE ᗩGE SE 500 KE KᗩᗩᖇE KᗩᗩᖇE ᑎOTE ᑎIKᗩᒪᑌᑎGᗩᗩ ᗷᕼOSᗪIKE💰💰🤩",
    "TEᖇI ᗰᗩᗩ KE SᗩTᕼ Sᑌᗩᖇ Kᗩ SE᙭ Kᗩᖇᗯᗩ ᗪᑌᑎGᗩᗩ EK SᗩTᕼ 6-6 ᗷᗩᑕᕼE ᗪEGI💰🔥😱",
    "TEᖇI ᗷᗩᕼEᑎ KI ᑕᕼᑌT ᗰEI ᗩᑭᑭᒪE Kᗩ 18ᗯ ᗯᗩᒪᗩ ᑕᕼᗩᖇGEᖇ 🔥🤩",
    "TEᖇI ᗷᗩᕼEᑎ KI Gᗩᗩᑎᗪ ᗰEI OᑎEᑭᒪᑌS Kᗩ ᗯᖇᗩᑭ ᑕᕼᗩᖇGEᖇ 30ᗯ ᕼIGᕼ ᑭOᗯEᖇ 💥😂😎",
    "TEᖇI ᗷᗩᕼEᑎ KI ᑕᕼᑌT KO ᗩᗰᗩᘔOᑎ SE OᖇᗪEᖇ KᗩᖇᑌᑎGᗩ 10 ᖇs ᗰEI ᗩᑌᖇ ᖴᒪIᑭKᗩᖇT ᑭE 20 ᖇS ᗰEI ᗷEᑕᕼ ᗪᑌᑎGᗩ🤮👿😈🤖",
    "TEᖇI ᗰᗩᗩ KI ᗷᗩᗪI ᗷᕼᑌᑎᗪ ᗰE ᘔOᗰᗩTO ᗪᗩᒪ KE SᑌᗷᗯᗩY Kᗩ ᗷᖴᖴ ᐯEG Sᑌᗷ ᑕOᗰᗷO [15ᑕᗰ , 16 IᑎᑕᕼEs ] OᖇᗪEᖇ ᑕOᗪ KᖇᐯᗩᑌᑎGᗩ Oᖇ TEᖇI ᗰᗩᗩ ᒍᗩᗷ ᗪIᒪIᐯEᖇY ᗪEᑎE ᗩYEGI Tᗩᗷ ᑌSᑭE ᒍᗩᗩᗪᑌ KᖇᑌᑎGᗩ Oᖇ ᖴIᖇ 9 ᗰOᑎTᕼ ᗷᗩᗩᗪ ᐯO EK Oᖇ ᖴᖇEE ᗪIᒪIᐯEᖇY ᗪEGI🙀👍🥳🔥",
    "TEᖇI ᗷᕼEᑎ KI ᑕᕼᑌT KᗩᗩᒪI🙁🤣💥",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰE ᑕᕼᗩᑎGES ᑕOᗰᗰIT KᖇᑌGᗩ ᖴIᖇ TEᖇI ᗷᕼEEᑎ KI ᑕᕼᑌT ᗩᑌTOᗰᗩTIᑕᗩᒪᒪY ᑌᑭᗪᗩTE ᕼOᒍᗩᗩYEGI🤖🙏🤔",
    "TEᖇI ᗰᗩᑌSI KE ᗷᕼOSᗪE ᗰEI IᑎᗪIᗩᑎ ᖇᗩIᒪᗯᗩY 🚂💥😂",
    "Tᑌ TEᖇI ᗷᗩᕼEᑎ TEᖇᗩ Kᕼᗩᑎᗪᗩᑎ Sᗩᗷ ᗷᗩᕼEᑎ KE ᒪᗩᗯᗪE ᖇᗩᑎᗪI ᕼᗩI ᖇᗩᑎᗪI 🤢✅🔥",
    "TEᖇI ᗷᗩᕼEᑎ KI ᑕᕼᑌT ᗰEI IOᑎIᑕ ᗷOᑎᗪ ᗷᗩᑎᗩ KE ᐯIᖇGIᑎITY ᒪOOSE Kᗩᖇᗯᗩ ᗪᑌᑎGᗩ ᑌSKI 📚 😎🤩",
    "TEᖇI ᖇᗩᑎᗪI ᗰᗩᗩ SE ᑭᑌᑕᕼᑎᗩ ᗷᗩᗩᑭ Kᗩ ᑎᗩᗩᗰ ᗷᗩᕼEᑎ KE ᒪOᗪEEEEE 🤩🥳😳",
    "Tᑌ ᗩᑌᖇ TEᖇI ᗰᗩᗩ ᗪOᑎO KI ᗷᕼOSᗪE ᗰEI ᗰETᖇO ᑕᕼᗩᒪᗯᗩ ᗪᑌᑎGᗩ ᗰᗩᗪᗩᖇ᙭ᕼOᗪ 🚇🤩😱🥶",
    "TEᖇI ᗰᗩᗩ KO ITᑎᗩ ᑕᕼOᗪᑌᑎGᗩ TEᖇᗩ ᗷᗩᗩᑭ ᗷᕼI ᑌSKO ᑭᗩᕼᑕᕼᗩᑎᗩᑎE SE ᗰᗩᑎᗩ Kᗩᖇ ᗪEGᗩ😂👿🤩",
    "TEᖇI ᗷᗩᕼEᑎ KE ᗷᕼOSᗪE ᗰEI ᕼᗩIᖇ ᗪᖇYEᖇ ᑕᕼᗩᒪᗩ ᗪᑌᑎGᗩᗩ💥🔥🔥",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗰEI TEᒪEGᖇᗩᗰ KI SᗩᖇI ᖇᗩᑎᗪIYOᑎ Kᗩ ᖇᗩᑎᗪI Kᕼᗩᑎᗩ KᕼOᒪ ᗪᑌᑎGᗩᗩ👿🤮😎",
    "TEᖇI ᗰᗩᗩ KI ᑕᕼᑌT ᗩᒪE᙭ᗩ ᗪᗩᒪ KEE ᗪᒍ ᗷᗩᒍᗩᑌᑎGᗩᗩᗩ 🎶 ⬆️🤩💥",
    "TEᖇI ᗰᗩᗩ KE ᗷᕼOSᗪE ᗰEI GITᕼᑌᗷ ᗪᗩᒪ KE ᗩᑭᑎᗩ ᗷOT ᕼOST KᗩᖇᑌᑎGᗩᗩ 🤩👊👤😍",
    "TEᖇI ᗷᗩᕼEᑎ Kᗩ ᐯᑭS ᗷᗩᑎᗩ KE 24*7 ᗷᗩSᕼ ᑕᕼᑌᗪᗩI ᑕOᗰᗰᗩᑎᗪ ᗪE ᗪᑌᑎGᗩᗩ 🤩💥🔥🔥",
    "TEᖇI ᗰᑌᗰᗰY KI ᑕᕼᑌT ᗰEI TEᖇE ᒪᗩᑎᗪ KO ᗪᗩᒪ KE KᗩᗩT ᗪᑌᑎGᗩ ᗰᗩᗪᗩᖇᑕᕼOᗪ 🔪😂🔥",
    "Sᑌᑎ TEᖇI ᗰᗩᗩ Kᗩ ᗷᕼOSᗪᗩ ᗩᑌᖇ TEᖇI ᗷᗩᕼEᑎ Kᗩ ᗷᕼI ᗷᕼOSᗪᗩ 👿😎👊",
    "TᑌᒍᕼE ᗪEKᕼ KE TEᖇI ᖇᗩᑎᗪI ᗷᗩᕼEᑎ ᑭE TᗩᖇᗩS ᗩTᗩ ᕼᗩI ᗰᑌᒍᕼE ᗷᗩᕼEᑎ KE ᒪOᗪEEEE 👿💥🤩🔥",
    "Sᑌᑎ ᗰᗩᗪᗩᖇᑕᕼOᗪ ᒍYᗩᗪᗩ ᑎᗩ ᑌᑕᕼᗩᒪ ᗰᗩᗩ ᑕᕼOᗪ ᗪEᑎGE EK ᗰIᑎ ᗰEI ✅🤣🔥🤩",
    "ᗩᑭᑎI ᗩᗰᗰᗩ SE ᑭᑌᑕᕼᑎᗩ ᑌSKO ᑌS KᗩᗩᒪI ᖇᗩᗩT ᗰEI Kᗩᑌᑎ ᑕᕼOᗪᑎEE ᗩYᗩ Tᕼᗩᗩᗩ! TEᖇE IS ᑭᗩᑭᗩ Kᗩ ᑎᗩᗩᗰ ᒪEGI 😂👿😳",
    "TOᕼᗩᖇ ᗷᗩᕼIᑎ ᑕᕼOᗪᑌ ᗷᗷᗩᕼEᑎ KE ᒪᗩᗯᗪE ᑌSᗰE ᗰITTI ᗪᗩᒪ KE ᑕEᗰEᑎT SE ᗷᕼᗩᖇ ᗪᑌ 🏠🤢🤩💥",
    "TᑌᒍᕼE ᗩᗷ TᗩK ᑎᗩᕼI Sᗰᒍᕼ ᗩYᗩ KI ᗰᗩI ᕼI ᕼᑌ TᑌᒍᕼE ᑭᗩIᗪᗩ KᗩᖇᑎE ᗯᗩᒪᗩ ᗷᕼOSᗪIKEE ᗩᑭᑎI ᗰᗩᗩ SE ᑭᑌᑕᕼ ᖇᗩᑎᗪI KE ᗷᗩᑕᕼEEEE 🤩👊👤😍",
    "TEᖇI ᗰᗩᗩ KE ᗷᕼOSᗪE ᗰEI SᑭOTIᖴY ᗪᗩᒪ KE ᒪOᖴI ᗷᗩᒍᗩᑌᑎGᗩ ᗪIᑎ ᗷᕼᗩᖇ 😍🎶🎶💥",
    "TEᖇI ᗰᗩᗩ Kᗩ ᑎᗩYᗩ ᖇᗩᑎᗪI Kᕼᗩᑎᗩ KᕼOᒪᑌᑎGᗩ ᑕᕼIᑎTᗩ ᗰᗩT Kᗩᖇ 👊🤣🤣😳",
    "TEᖇᗩ ᗷᗩᗩᑭ ᕼᑌ ᗷᕼOSᗪIKE TEᖇI ᗰᗩᗩ KO ᖇᗩᑎᗪI KᕼᗩᑎE ᑭE ᑕᕼᑌᗪᗯᗩ KE ᑌS ᑭᗩISE KI ᗪᗩᗩᖇᑌ ᑭEETᗩ ᕼᑌ 🍷🤩🔥",
    "TEᖇI ᗷᗩᕼEᑎ KI ᑕᕼᑌT ᗰEI ᗩᑭᑎᗩ ᗷᗩᗪᗩ Sᗩ ᒪOᗪᗩ GᕼᑌSSᗩ ᗪᑌᑎGᗩᗩ Kᗩᒪᒪᗩᗩᑭ KE ᗰᗩᖇ ᒍᗩYEGI 🤩😳😳🔥",
    "TOᕼᗩᖇ ᗰᑌᗰᗰY KI ᑕᕼᑌT ᗰEI ᑭᑌᖇI KI ᑭᑌᖇI KIᑎGᖴISᕼEᖇ KI ᗷOTTᒪE ᗪᗩᒪ KE TOᗪ ᗪᑌᑎGᗩ ᗩᑎᗪEᖇ ᕼI 😱😂🤩",
    "TEᖇI ᗰᗩᗩ KO ITᑎᗩ ᑕᕼOᗪᑌᑎGᗩ KI SᗩᑭᑎE ᗰEI ᗷᕼI ᗰEᖇI ᑕᕼᑌᗪᗩI Yᗩᗩᗪ KᗩᖇEGI ᖇᗩᑎᗪI 🥳😍👊💥",
    "TEᖇI ᗰᑌᗰᗰY ᗩᑌᖇ ᗷᗩᕼEᑎ KO ᗪᗩᑌᗪᗩ ᗪᗩᑌᗪᗩ ᑎE ᑕᕼOᗪᑌᑎGᗩ ᑌᑎKE ᑎO ᗷOᒪᑎE ᑭE ᗷᕼI ᒪᗩᑎᗪ GᕼᑌSᗩ ᗪᑌᑎGᗩ ᗩᑎᗪEᖇ TᗩK 😎😎🤣🔥",
    "TEᖇI ᗰᑌᗰᗰY KI ᑕᕼᑌT KO OᑎᒪIᑎE Oᒪ᙭ ᑭE ᗷEᑕᕼᑌᑎGᗩ ᗩᑌᖇ ᑭᗩISE SE TEᖇI ᗷᗩᕼEᑎ Kᗩ KOTᕼᗩ KᕼOᒪ ᗪᑌᑎGᗩ 😎🤩😝😍",
    "TEᖇI ᗰᗩᗩ KE ᗷᕼOSᗪᗩ ITᑎᗩ ᑕᕼOᗪᑌᑎGᗩ KI Tᑌ ᑕᗩᕼ KE ᗷᕼI ᗯO ᗰᗩST ᑕᕼᑌᗪᗩI SE ᗪᑌᖇ ᑎᕼI ᒍᗩ ᑭᗩYEGᗩᗩ 😏😏🤩😍",
    "Sᑌᑎ ᗷE ᖇᗩᑎᗪI KI ᗩᑌᒪᗩᗩᗪ Tᑌ ᗩᑭᑎI ᗷᗩᕼEᑎ SE SEEKᕼ Kᑌᑕᕼ KᗩISE Gᗩᗩᑎᗪ ᗰᗩᖇᗯᗩTE ᕼᗩI😏🤬🔥💥",
    "TEᖇI ᗰᗩᗩ Kᗩ Yᗩᗩᖇ ᕼᑌ ᗰEI ᗩᑌᖇ TEᖇI ᗷᗩᕼEᑎ Kᗩ ᑭYᗩᗩᖇ ᕼᑌ ᗰEI ᗩᒍᗩ ᗰEᖇᗩ ᒪᗩᑎᗪ ᑕᕼOOS ᒪE 🤩🤣💥",
    "TEᖇI ᗰᗩᗩ Kᗩᗩ ᗷᕼOSᗪᗩ ᗰEE ᗷᖇOᗯᑎ SᑌGᗩᖇ ᗪᗩᒪ KE ᑕᕼODᑌ",
]
